//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TemplateLexer.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class TemplateLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		OPEN1=1, OPEN2=2, CLOSE1=3, CLOSE2=4;
	public const int
		CODE_MODE=1, PROP_MODE=2;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE", "CODE_MODE", "PROP_MODE"
	};

	public static readonly string[] ruleNames = {
		"OPEN1", "OPEN2", "CLOSE1", "CLOSE2"
	};


	public TemplateLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public TemplateLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'<%'", "'${'", "'%>'", "'}'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "OPEN1", "OPEN2", "CLOSE1", "CLOSE2"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "TemplateLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static TemplateLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x6', ' ', '\b', '\x1', '\b', '\x1', '\b', '\x1', '\x4', 
		'\x2', '\t', '\x2', '\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', 
		'\x4', '\x5', '\t', '\x5', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x2', '\x2', '\x6', '\x5', '\x3', '\a', '\x4', '\t', '\x5', '\v', 
		'\x6', '\x5', '\x2', '\x3', '\x4', '\x2', '\x2', '\x1D', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x3', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x4', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x5', '\r', '\x3', '\x2', '\x2', '\x2', '\a', '\x12', '\x3', '\x2', '\x2', 
		'\x2', '\t', '\x17', '\x3', '\x2', '\x2', '\x2', '\v', '\x1C', '\x3', 
		'\x2', '\x2', '\x2', '\r', '\xE', '\a', '>', '\x2', '\x2', '\xE', '\xF', 
		'\a', '\'', '\x2', '\x2', '\xF', '\x10', '\x3', '\x2', '\x2', '\x2', '\x10', 
		'\x11', '\b', '\x2', '\x2', '\x2', '\x11', '\x6', '\x3', '\x2', '\x2', 
		'\x2', '\x12', '\x13', '\a', '&', '\x2', '\x2', '\x13', '\x14', '\a', 
		'}', '\x2', '\x2', '\x14', '\x15', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'\x16', '\b', '\x3', '\x3', '\x2', '\x16', '\b', '\x3', '\x2', '\x2', 
		'\x2', '\x17', '\x18', '\a', '\'', '\x2', '\x2', '\x18', '\x19', '\a', 
		'@', '\x2', '\x2', '\x19', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x1A', 
		'\x1B', '\b', '\x4', '\x4', '\x2', '\x1B', '\n', '\x3', '\x2', '\x2', 
		'\x2', '\x1C', '\x1D', '\a', '\x7F', '\x2', '\x2', '\x1D', '\x1E', '\x3', 
		'\x2', '\x2', '\x2', '\x1E', '\x1F', '\b', '\x5', '\x4', '\x2', '\x1F', 
		'\f', '\x3', '\x2', '\x2', '\x2', '\x5', '\x2', '\x3', '\x4', '\x5', '\a', 
		'\x3', '\x2', '\a', '\x4', '\x2', '\x6', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
