//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TemplateParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class TemplateParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		OPEN=1, TEXT=2, CLOSE=3, INTEGER=4, FLOAT=5, BOOL=6, SET_DIV=7, SET_MUL=8, 
		SET_MOD=9, SET_ADD=10, SET_SUB=11, SET_SHIFTL=12, SET_SHIFTR=13, SET_BIT_AND=14, 
		SET_BIT_XOR=15, SET_BIT_OR=16, STRING=17, BRACE_L=18, BRACE_R=19, INCREMENT=20, 
		DECREMENT=21, MUL=22, DIV=23, MOD=24, ADD=25, SUB=26, PARENTHESES_L=27, 
		PARENTHESES_R=28, DOT=29, COMMA=30, NOTEQUAL=31, LOGIC_NOT=32, BIT_INVERT=33, 
		SHIFTL=34, SHIFTR=35, LESS=36, LESSEQUAL=37, GREATER=38, GREATEREQUAL=39, 
		EQUAL=40, LOGIC_AND=41, LOGIC_OR=42, BIT_AND=43, BIT_OR=44, BIT_XOR=45, 
		SET=46, COLON=47, SEMICOLON=48, VAR=49, IF=50, SWITCH=51, CASE=52, WHILE=53, 
		DO=54, FOR=55, FOREACH=56, IN=57, BREAK=58, CONTINUE=59, RETURN=60, IDENT=61, 
		COMMENT=62, WS=63;
	public const int
		RULE_document = 0, RULE_code = 1, RULE_var = 2, RULE_if = 3, RULE_switch = 4, 
		RULE_while = 5, RULE_dowhile = 6, RULE_for = 7, RULE_foreach = 8, RULE_expr = 9, 
		RULE_exprCall = 10, RULE_exprProp = 11, RULE_exprValue = 12;
	public static readonly string[] ruleNames = {
		"document", "code", "var", "if", "switch", "while", "dowhile", "for", 
		"foreach", "expr", "exprCall", "exprProp", "exprValue"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, "'/='", "'*='", "'%='", "'+='", 
		"'-='", "'<<='", "'>>='", "'&='", "'^='", "'|='", null, "'{'", "'}'", 
		"'++'", "'--'", "'*'", "'/'", "'%'", "'+'", "'-'", "'('", "')'", "'.'", 
		"','", "'!='", "'!'", "'~'", "'<<'", "'>>'", "'<'", "'<='", "'>'", "'>='", 
		"'=='", "'&&'", "'||'", "'&'", "'|'", "'^'", "'='", "':'", "';'", "'var'", 
		"'if'", "'switch'", "'case'", "'while'", "'do'", "'for'", "'foreach'", 
		"'in'", "'break'", "'continue'", "'return'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "OPEN", "TEXT", "CLOSE", "INTEGER", "FLOAT", "BOOL", "SET_DIV", 
		"SET_MUL", "SET_MOD", "SET_ADD", "SET_SUB", "SET_SHIFTL", "SET_SHIFTR", 
		"SET_BIT_AND", "SET_BIT_XOR", "SET_BIT_OR", "STRING", "BRACE_L", "BRACE_R", 
		"INCREMENT", "DECREMENT", "MUL", "DIV", "MOD", "ADD", "SUB", "PARENTHESES_L", 
		"PARENTHESES_R", "DOT", "COMMA", "NOTEQUAL", "LOGIC_NOT", "BIT_INVERT", 
		"SHIFTL", "SHIFTR", "LESS", "LESSEQUAL", "GREATER", "GREATEREQUAL", "EQUAL", 
		"LOGIC_AND", "LOGIC_OR", "BIT_AND", "BIT_OR", "BIT_XOR", "SET", "COLON", 
		"SEMICOLON", "VAR", "IF", "SWITCH", "CASE", "WHILE", "DO", "FOR", "FOREACH", 
		"IN", "BREAK", "CONTINUE", "RETURN", "IDENT", "COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "TemplateParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static TemplateParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public TemplateParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public TemplateParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class DocumentContext : ParserRuleContext {
		public CodeContext[] code() {
			return GetRuleContexts<CodeContext>();
		}
		public CodeContext code(int i) {
			return GetRuleContext<CodeContext>(i);
		}
		public DocumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_document; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterDocument(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitDocument(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDocument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DocumentContext document() {
		DocumentContext _localctx = new DocumentContext(Context, State);
		EnterRule(_localctx, 0, RULE_document);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 29;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TEXT) | (1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << VAR) | (1L << IF) | (1L << SWITCH) | (1L << WHILE) | (1L << DO) | (1L << FOR) | (1L << FOREACH) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << IDENT))) != 0)) {
				{
				{
				State = 26; code();
				}
				}
				State = 31;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CodeContext : ParserRuleContext {
		public VarContext var() {
			return GetRuleContext<VarContext>(0);
		}
		public IfContext @if() {
			return GetRuleContext<IfContext>(0);
		}
		public SwitchContext @switch() {
			return GetRuleContext<SwitchContext>(0);
		}
		public WhileContext @while() {
			return GetRuleContext<WhileContext>(0);
		}
		public DowhileContext dowhile() {
			return GetRuleContext<DowhileContext>(0);
		}
		public ForContext @for() {
			return GetRuleContext<ForContext>(0);
		}
		public ForeachContext @foreach() {
			return GetRuleContext<ForeachContext>(0);
		}
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode TEXT() { return GetToken(TemplateParser.TEXT, 0); }
		public ITerminalNode BREAK() { return GetToken(TemplateParser.BREAK, 0); }
		public ITerminalNode CONTINUE() { return GetToken(TemplateParser.CONTINUE, 0); }
		public ITerminalNode RETURN() { return GetToken(TemplateParser.RETURN, 0); }
		public CodeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_code; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterCode(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitCode(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCode(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CodeContext code() {
		CodeContext _localctx = new CodeContext(Context, State);
		EnterRule(_localctx, 2, RULE_code);
		try {
			State = 44;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case VAR:
				EnterOuterAlt(_localctx, 1);
				{
				State = 32; var();
				}
				break;
			case IF:
				EnterOuterAlt(_localctx, 2);
				{
				State = 33; @if();
				}
				break;
			case SWITCH:
				EnterOuterAlt(_localctx, 3);
				{
				State = 34; @switch();
				}
				break;
			case WHILE:
				EnterOuterAlt(_localctx, 4);
				{
				State = 35; @while();
				}
				break;
			case DO:
				EnterOuterAlt(_localctx, 5);
				{
				State = 36; dowhile();
				}
				break;
			case FOR:
				EnterOuterAlt(_localctx, 6);
				{
				State = 37; @for();
				}
				break;
			case FOREACH:
				EnterOuterAlt(_localctx, 7);
				{
				State = 38; @foreach();
				}
				break;
			case INTEGER:
			case FLOAT:
			case BOOL:
			case STRING:
			case INCREMENT:
			case DECREMENT:
			case SUB:
			case PARENTHESES_L:
			case LOGIC_NOT:
			case BIT_INVERT:
			case IDENT:
				EnterOuterAlt(_localctx, 8);
				{
				State = 39; expr(0);
				}
				break;
			case TEXT:
				EnterOuterAlt(_localctx, 9);
				{
				State = 40; Match(TEXT);
				}
				break;
			case BREAK:
				EnterOuterAlt(_localctx, 10);
				{
				State = 41; Match(BREAK);
				}
				break;
			case CONTINUE:
				EnterOuterAlt(_localctx, 11);
				{
				State = 42; Match(CONTINUE);
				}
				break;
			case RETURN:
				EnterOuterAlt(_localctx, 12);
				{
				State = 43; Match(RETURN);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarContext : ParserRuleContext {
		public IToken keyword;
		public IToken key;
		public ITerminalNode SEMICOLON() { return GetToken(TemplateParser.SEMICOLON, 0); }
		public ITerminalNode VAR() { return GetToken(TemplateParser.VAR, 0); }
		public ITerminalNode IDENT() { return GetToken(TemplateParser.IDENT, 0); }
		public ITerminalNode EQUAL() { return GetToken(TemplateParser.EQUAL, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public VarContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterVar(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitVar(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VarContext var() {
		VarContext _localctx = new VarContext(Context, State);
		EnterRule(_localctx, 4, RULE_var);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 46; _localctx.keyword = Match(VAR);
			State = 47; _localctx.key = Match(IDENT);
			State = 50;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==EQUAL) {
				{
				State = 48; Match(EQUAL);
				State = 49; expr(0);
				}
			}

			State = 52; Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfContext : ParserRuleContext {
		public IToken keyword;
		public ExprContext condition;
		public ITerminalNode PARENTHESES_L() { return GetToken(TemplateParser.PARENTHESES_L, 0); }
		public ITerminalNode PARENTHESES_R() { return GetToken(TemplateParser.PARENTHESES_R, 0); }
		public ITerminalNode BRACE_L() { return GetToken(TemplateParser.BRACE_L, 0); }
		public ITerminalNode BRACE_R() { return GetToken(TemplateParser.BRACE_R, 0); }
		public ITerminalNode IF() { return GetToken(TemplateParser.IF, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public CodeContext[] code() {
			return GetRuleContexts<CodeContext>();
		}
		public CodeContext code(int i) {
			return GetRuleContext<CodeContext>(i);
		}
		public IfContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_if; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterIf(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitIf(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIf(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IfContext @if() {
		IfContext _localctx = new IfContext(Context, State);
		EnterRule(_localctx, 6, RULE_if);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 54; _localctx.keyword = Match(IF);
			State = 55; Match(PARENTHESES_L);
			State = 56; _localctx.condition = expr(0);
			State = 57; Match(PARENTHESES_R);
			State = 58; Match(BRACE_L);
			State = 62;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TEXT) | (1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << VAR) | (1L << IF) | (1L << SWITCH) | (1L << WHILE) | (1L << DO) | (1L << FOR) | (1L << FOREACH) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << IDENT))) != 0)) {
				{
				{
				State = 59; code();
				}
				}
				State = 64;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 65; Match(BRACE_R);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SwitchContext : ParserRuleContext {
		public IToken keywordA;
		public ExprContext condition;
		public IToken _CASE;
		public IList<IToken> _keywordB = new List<IToken>();
		public ITerminalNode PARENTHESES_L() { return GetToken(TemplateParser.PARENTHESES_L, 0); }
		public ITerminalNode PARENTHESES_R() { return GetToken(TemplateParser.PARENTHESES_R, 0); }
		public ITerminalNode BRACE_L() { return GetToken(TemplateParser.BRACE_L, 0); }
		public ITerminalNode BRACE_R() { return GetToken(TemplateParser.BRACE_R, 0); }
		public ITerminalNode SWITCH() { return GetToken(TemplateParser.SWITCH, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode[] COLON() { return GetTokens(TemplateParser.COLON); }
		public ITerminalNode COLON(int i) {
			return GetToken(TemplateParser.COLON, i);
		}
		public ITerminalNode[] CASE() { return GetTokens(TemplateParser.CASE); }
		public ITerminalNode CASE(int i) {
			return GetToken(TemplateParser.CASE, i);
		}
		public ITerminalNode[] BREAK() { return GetTokens(TemplateParser.BREAK); }
		public ITerminalNode BREAK(int i) {
			return GetToken(TemplateParser.BREAK, i);
		}
		public SwitchContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_switch; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterSwitch(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitSwitch(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSwitch(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SwitchContext @switch() {
		SwitchContext _localctx = new SwitchContext(Context, State);
		EnterRule(_localctx, 8, RULE_switch);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 67; _localctx.keywordA = Match(SWITCH);
			State = 68; Match(PARENTHESES_L);
			State = 69; _localctx.condition = expr(0);
			State = 70; Match(PARENTHESES_R);
			State = 71; Match(BRACE_L);
			State = 81;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==CASE) {
				{
				{
				State = 72; _localctx._CASE = Match(CASE);
				_localctx._keywordB.Add(_localctx._CASE);
				State = 73; expr(0);
				State = 74; Match(COLON);
				State = 75; expr(0);
				State = 77;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==BREAK) {
					{
					State = 76; Match(BREAK);
					}
				}

				}
				}
				State = 83;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 84; Match(BRACE_R);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WhileContext : ParserRuleContext {
		public IToken keyword;
		public ExprContext condition;
		public ITerminalNode PARENTHESES_L() { return GetToken(TemplateParser.PARENTHESES_L, 0); }
		public ITerminalNode PARENTHESES_R() { return GetToken(TemplateParser.PARENTHESES_R, 0); }
		public ITerminalNode BRACE_L() { return GetToken(TemplateParser.BRACE_L, 0); }
		public ITerminalNode BRACE_R() { return GetToken(TemplateParser.BRACE_R, 0); }
		public ITerminalNode WHILE() { return GetToken(TemplateParser.WHILE, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public CodeContext[] code() {
			return GetRuleContexts<CodeContext>();
		}
		public CodeContext code(int i) {
			return GetRuleContext<CodeContext>(i);
		}
		public WhileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_while; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterWhile(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitWhile(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhile(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public WhileContext @while() {
		WhileContext _localctx = new WhileContext(Context, State);
		EnterRule(_localctx, 10, RULE_while);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 86; _localctx.keyword = Match(WHILE);
			State = 87; Match(PARENTHESES_L);
			State = 88; _localctx.condition = expr(0);
			State = 89; Match(PARENTHESES_R);
			State = 90; Match(BRACE_L);
			State = 94;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TEXT) | (1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << VAR) | (1L << IF) | (1L << SWITCH) | (1L << WHILE) | (1L << DO) | (1L << FOR) | (1L << FOREACH) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << IDENT))) != 0)) {
				{
				{
				State = 91; code();
				}
				}
				State = 96;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 97; Match(BRACE_R);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DowhileContext : ParserRuleContext {
		public IToken keywordA;
		public IToken keywordB;
		public ExprContext condition;
		public ITerminalNode BRACE_L() { return GetToken(TemplateParser.BRACE_L, 0); }
		public ITerminalNode BRACE_R() { return GetToken(TemplateParser.BRACE_R, 0); }
		public ITerminalNode PARENTHESES_L() { return GetToken(TemplateParser.PARENTHESES_L, 0); }
		public ITerminalNode PARENTHESES_R() { return GetToken(TemplateParser.PARENTHESES_R, 0); }
		public ITerminalNode DO() { return GetToken(TemplateParser.DO, 0); }
		public ITerminalNode WHILE() { return GetToken(TemplateParser.WHILE, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public CodeContext[] code() {
			return GetRuleContexts<CodeContext>();
		}
		public CodeContext code(int i) {
			return GetRuleContext<CodeContext>(i);
		}
		public DowhileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dowhile; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterDowhile(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitDowhile(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDowhile(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DowhileContext dowhile() {
		DowhileContext _localctx = new DowhileContext(Context, State);
		EnterRule(_localctx, 12, RULE_dowhile);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 99; _localctx.keywordA = Match(DO);
			State = 100; Match(BRACE_L);
			State = 104;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TEXT) | (1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << VAR) | (1L << IF) | (1L << SWITCH) | (1L << WHILE) | (1L << DO) | (1L << FOR) | (1L << FOREACH) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << IDENT))) != 0)) {
				{
				{
				State = 101; code();
				}
				}
				State = 106;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 107; Match(BRACE_R);
			State = 108; _localctx.keywordB = Match(WHILE);
			State = 109; Match(PARENTHESES_L);
			State = 110; _localctx.condition = expr(0);
			State = 111; Match(PARENTHESES_R);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForContext : ParserRuleContext {
		public IToken keyword;
		public ITerminalNode PARENTHESES_L() { return GetToken(TemplateParser.PARENTHESES_L, 0); }
		public ITerminalNode[] SEMICOLON() { return GetTokens(TemplateParser.SEMICOLON); }
		public ITerminalNode SEMICOLON(int i) {
			return GetToken(TemplateParser.SEMICOLON, i);
		}
		public ITerminalNode PARENTHESES_R() { return GetToken(TemplateParser.PARENTHESES_R, 0); }
		public ITerminalNode BRACE_L() { return GetToken(TemplateParser.BRACE_L, 0); }
		public ITerminalNode BRACE_R() { return GetToken(TemplateParser.BRACE_R, 0); }
		public ITerminalNode FOR() { return GetToken(TemplateParser.FOR, 0); }
		public CodeContext[] code() {
			return GetRuleContexts<CodeContext>();
		}
		public CodeContext code(int i) {
			return GetRuleContext<CodeContext>(i);
		}
		public ForContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_for; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterFor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitFor(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFor(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ForContext @for() {
		ForContext _localctx = new ForContext(Context, State);
		EnterRule(_localctx, 14, RULE_for);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 113; _localctx.keyword = Match(FOR);
			State = 114; Match(PARENTHESES_L);
			State = 116;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TEXT) | (1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << VAR) | (1L << IF) | (1L << SWITCH) | (1L << WHILE) | (1L << DO) | (1L << FOR) | (1L << FOREACH) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << IDENT))) != 0)) {
				{
				State = 115; code();
				}
			}

			State = 118; Match(SEMICOLON);
			State = 120;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TEXT) | (1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << VAR) | (1L << IF) | (1L << SWITCH) | (1L << WHILE) | (1L << DO) | (1L << FOR) | (1L << FOREACH) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << IDENT))) != 0)) {
				{
				State = 119; code();
				}
			}

			State = 122; Match(SEMICOLON);
			State = 124;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TEXT) | (1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << VAR) | (1L << IF) | (1L << SWITCH) | (1L << WHILE) | (1L << DO) | (1L << FOR) | (1L << FOREACH) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << IDENT))) != 0)) {
				{
				State = 123; code();
				}
			}

			State = 126; Match(PARENTHESES_R);
			State = 127; Match(BRACE_L);
			State = 131;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TEXT) | (1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << VAR) | (1L << IF) | (1L << SWITCH) | (1L << WHILE) | (1L << DO) | (1L << FOR) | (1L << FOREACH) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << IDENT))) != 0)) {
				{
				{
				State = 128; code();
				}
				}
				State = 133;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 134; Match(BRACE_R);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForeachContext : ParserRuleContext {
		public IToken keywordA;
		public IToken keywordB;
		public ITerminalNode PARENTHESES_L() { return GetToken(TemplateParser.PARENTHESES_L, 0); }
		public CodeContext[] code() {
			return GetRuleContexts<CodeContext>();
		}
		public CodeContext code(int i) {
			return GetRuleContext<CodeContext>(i);
		}
		public ITerminalNode PARENTHESES_R() { return GetToken(TemplateParser.PARENTHESES_R, 0); }
		public ITerminalNode BRACE_L() { return GetToken(TemplateParser.BRACE_L, 0); }
		public ITerminalNode BRACE_R() { return GetToken(TemplateParser.BRACE_R, 0); }
		public ITerminalNode FOREACH() { return GetToken(TemplateParser.FOREACH, 0); }
		public ITerminalNode IN() { return GetToken(TemplateParser.IN, 0); }
		public ForeachContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_foreach; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterForeach(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitForeach(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitForeach(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ForeachContext @foreach() {
		ForeachContext _localctx = new ForeachContext(Context, State);
		EnterRule(_localctx, 16, RULE_foreach);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 136; _localctx.keywordA = Match(FOREACH);
			State = 137; Match(PARENTHESES_L);
			State = 138; code();
			State = 139; _localctx.keywordB = Match(IN);
			State = 140; code();
			State = 141; Match(PARENTHESES_R);
			State = 142; Match(BRACE_L);
			State = 146;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TEXT) | (1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << VAR) | (1L << IF) | (1L << SWITCH) | (1L << WHILE) | (1L << DO) | (1L << FOR) | (1L << FOREACH) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << IDENT))) != 0)) {
				{
				{
				State = 143; code();
				}
				}
				State = 148;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 149; Match(BRACE_R);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext r;
		public ExprContext l;
		public ExprCallContext call;
		public ExprPropContext prop;
		public IToken op;
		public IToken t;
		public ExprValueContext v;
		public ITerminalNode PARENTHESES_L() { return GetToken(TemplateParser.PARENTHESES_L, 0); }
		public ITerminalNode PARENTHESES_R() { return GetToken(TemplateParser.PARENTHESES_R, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ExprCallContext exprCall() {
			return GetRuleContext<ExprCallContext>(0);
		}
		public ExprPropContext exprProp() {
			return GetRuleContext<ExprPropContext>(0);
		}
		public ITerminalNode SUB() { return GetToken(TemplateParser.SUB, 0); }
		public ITerminalNode IDENT() { return GetToken(TemplateParser.IDENT, 0); }
		public ITerminalNode INCREMENT() { return GetToken(TemplateParser.INCREMENT, 0); }
		public ITerminalNode DECREMENT() { return GetToken(TemplateParser.DECREMENT, 0); }
		public ITerminalNode LOGIC_NOT() { return GetToken(TemplateParser.LOGIC_NOT, 0); }
		public ITerminalNode BIT_INVERT() { return GetToken(TemplateParser.BIT_INVERT, 0); }
		public ExprValueContext exprValue() {
			return GetRuleContext<ExprValueContext>(0);
		}
		public ITerminalNode MUL() { return GetToken(TemplateParser.MUL, 0); }
		public ITerminalNode DIV() { return GetToken(TemplateParser.DIV, 0); }
		public ITerminalNode MOD() { return GetToken(TemplateParser.MOD, 0); }
		public ITerminalNode ADD() { return GetToken(TemplateParser.ADD, 0); }
		public ITerminalNode SHIFTL() { return GetToken(TemplateParser.SHIFTL, 0); }
		public ITerminalNode SHIFTR() { return GetToken(TemplateParser.SHIFTR, 0); }
		public ITerminalNode LESS() { return GetToken(TemplateParser.LESS, 0); }
		public ITerminalNode LESSEQUAL() { return GetToken(TemplateParser.LESSEQUAL, 0); }
		public ITerminalNode GREATER() { return GetToken(TemplateParser.GREATER, 0); }
		public ITerminalNode GREATEREQUAL() { return GetToken(TemplateParser.GREATEREQUAL, 0); }
		public ITerminalNode EQUAL() { return GetToken(TemplateParser.EQUAL, 0); }
		public ITerminalNode NOTEQUAL() { return GetToken(TemplateParser.NOTEQUAL, 0); }
		public ITerminalNode BIT_AND() { return GetToken(TemplateParser.BIT_AND, 0); }
		public ITerminalNode BIT_XOR() { return GetToken(TemplateParser.BIT_XOR, 0); }
		public ITerminalNode BIT_OR() { return GetToken(TemplateParser.BIT_OR, 0); }
		public ITerminalNode LOGIC_AND() { return GetToken(TemplateParser.LOGIC_AND, 0); }
		public ITerminalNode LOGIC_OR() { return GetToken(TemplateParser.LOGIC_OR, 0); }
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 18;
		EnterRecursionRule(_localctx, 18, RULE_expr, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 173;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 152; Match(PARENTHESES_L);
				State = 153; _localctx.r = expr(0);
				State = 154; Match(PARENTHESES_R);
				}
				break;
			case 2:
				{
				State = 156; _localctx.call = exprCall();
				}
				break;
			case 3:
				{
				State = 157; _localctx.prop = exprProp();
				}
				break;
			case 4:
				{
				State = 158; _localctx.op = Match(SUB);
				State = 159; _localctx.r = expr(27);
				}
				break;
			case 5:
				{
				State = 160; Match(PARENTHESES_L);
				State = 161; _localctx.t = Match(IDENT);
				State = 162; Match(PARENTHESES_R);
				State = 163; _localctx.r = expr(26);
				}
				break;
			case 6:
				{
				State = 164; _localctx.op = Match(INCREMENT);
				State = 165; _localctx.r = expr(25);
				}
				break;
			case 7:
				{
				State = 166; _localctx.op = Match(DECREMENT);
				State = 167; _localctx.r = expr(23);
				}
				break;
			case 8:
				{
				State = 168; _localctx.op = Match(LOGIC_NOT);
				State = 169; _localctx.r = expr(21);
				}
				break;
			case 9:
				{
				State = 170; _localctx.op = Match(BIT_INVERT);
				State = 171; _localctx.r = expr(20);
				}
				break;
			case 10:
				{
				State = 172; _localctx.v = exprValue();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 235;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 233;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
					case 1:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 175;
						if (!(Precpred(Context, 19))) throw new FailedPredicateException(this, "Precpred(Context, 19)");
						State = 176; _localctx.op = Match(MUL);
						State = 177; _localctx.r = expr(20);
						}
						break;
					case 2:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 178;
						if (!(Precpred(Context, 18))) throw new FailedPredicateException(this, "Precpred(Context, 18)");
						State = 179; _localctx.op = Match(DIV);
						State = 180; _localctx.r = expr(19);
						}
						break;
					case 3:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 181;
						if (!(Precpred(Context, 17))) throw new FailedPredicateException(this, "Precpred(Context, 17)");
						State = 182; _localctx.op = Match(MOD);
						State = 183; _localctx.r = expr(18);
						}
						break;
					case 4:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 184;
						if (!(Precpred(Context, 16))) throw new FailedPredicateException(this, "Precpred(Context, 16)");
						State = 185; _localctx.op = Match(ADD);
						State = 186; _localctx.r = expr(17);
						}
						break;
					case 5:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 187;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 188; _localctx.op = Match(SUB);
						State = 189; _localctx.r = expr(16);
						}
						break;
					case 6:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 190;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 191; _localctx.op = Match(SHIFTL);
						State = 192; _localctx.r = expr(15);
						}
						break;
					case 7:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 193;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 194; _localctx.op = Match(SHIFTR);
						State = 195; _localctx.r = expr(14);
						}
						break;
					case 8:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 196;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 197; _localctx.op = Match(LESS);
						State = 198; _localctx.r = expr(13);
						}
						break;
					case 9:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 199;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 200; _localctx.op = Match(LESSEQUAL);
						State = 201; _localctx.r = expr(12);
						}
						break;
					case 10:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 202;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 203; _localctx.op = Match(GREATER);
						State = 204; _localctx.r = expr(11);
						}
						break;
					case 11:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 205;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 206; _localctx.op = Match(GREATEREQUAL);
						State = 207; _localctx.r = expr(10);
						}
						break;
					case 12:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 208;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 209; _localctx.op = Match(EQUAL);
						State = 210; _localctx.r = expr(9);
						}
						break;
					case 13:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 211;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 212; _localctx.op = Match(NOTEQUAL);
						State = 213; _localctx.r = expr(8);
						}
						break;
					case 14:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 214;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 215; _localctx.op = Match(BIT_AND);
						State = 216; _localctx.r = expr(7);
						}
						break;
					case 15:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 217;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 218; _localctx.op = Match(BIT_XOR);
						State = 219; _localctx.r = expr(6);
						}
						break;
					case 16:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 220;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 221; _localctx.op = Match(BIT_OR);
						State = 222; _localctx.r = expr(5);
						}
						break;
					case 17:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 223;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 224; _localctx.op = Match(LOGIC_AND);
						State = 225; _localctx.r = expr(4);
						}
						break;
					case 18:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 226;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 227; _localctx.op = Match(LOGIC_OR);
						State = 228; _localctx.r = expr(3);
						}
						break;
					case 19:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.r = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 229;
						if (!(Precpred(Context, 24))) throw new FailedPredicateException(this, "Precpred(Context, 24)");
						State = 230; _localctx.op = Match(INCREMENT);
						}
						break;
					case 20:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.r = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 231;
						if (!(Precpred(Context, 22))) throw new FailedPredicateException(this, "Precpred(Context, 22)");
						State = 232; _localctx.op = Match(DECREMENT);
						}
						break;
					}
					} 
				}
				State = 237;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ExprCallContext : ParserRuleContext {
		public IToken _IDENT;
		public IList<IToken> _names = new List<IToken>();
		public IToken op;
		public ExprContext _expr;
		public IList<ExprContext> _args = new List<ExprContext>();
		public ITerminalNode PARENTHESES_L() { return GetToken(TemplateParser.PARENTHESES_L, 0); }
		public ITerminalNode PARENTHESES_R() { return GetToken(TemplateParser.PARENTHESES_R, 0); }
		public ITerminalNode[] IDENT() { return GetTokens(TemplateParser.IDENT); }
		public ITerminalNode IDENT(int i) {
			return GetToken(TemplateParser.IDENT, i);
		}
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode[] DOT() { return GetTokens(TemplateParser.DOT); }
		public ITerminalNode DOT(int i) {
			return GetToken(TemplateParser.DOT, i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(TemplateParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(TemplateParser.COMMA, i);
		}
		public ExprCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_exprCall; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterExprCall(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitExprCall(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExprCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprCallContext exprCall() {
		ExprCallContext _localctx = new ExprCallContext(Context, State);
		EnterRule(_localctx, 20, RULE_exprCall);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 238; _localctx._IDENT = Match(IDENT);
			_localctx._names.Add(_localctx._IDENT);
			State = 243;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==DOT) {
				{
				{
				State = 239; _localctx.op = Match(DOT);
				State = 240; _localctx._IDENT = Match(IDENT);
				_localctx._names.Add(_localctx._IDENT);
				}
				}
				State = 245;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 246; Match(PARENTHESES_L);
			{
			State = 247; _localctx._expr = expr(0);
			_localctx._args.Add(_localctx._expr);
			State = 252;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 248; Match(COMMA);
				State = 249; _localctx._expr = expr(0);
				_localctx._args.Add(_localctx._expr);
				}
				}
				State = 254;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
			State = 255; Match(PARENTHESES_R);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprPropContext : ParserRuleContext {
		public IToken _IDENT;
		public IList<IToken> _names = new List<IToken>();
		public IToken op;
		public ITerminalNode[] IDENT() { return GetTokens(TemplateParser.IDENT); }
		public ITerminalNode IDENT(int i) {
			return GetToken(TemplateParser.IDENT, i);
		}
		public ITerminalNode[] DOT() { return GetTokens(TemplateParser.DOT); }
		public ITerminalNode DOT(int i) {
			return GetToken(TemplateParser.DOT, i);
		}
		public ExprPropContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_exprProp; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterExprProp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitExprProp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExprProp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprPropContext exprProp() {
		ExprPropContext _localctx = new ExprPropContext(Context, State);
		EnterRule(_localctx, 22, RULE_exprProp);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 257; _localctx._IDENT = Match(IDENT);
			_localctx._names.Add(_localctx._IDENT);
			State = 262;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,18,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 258; _localctx.op = Match(DOT);
					State = 259; _localctx._IDENT = Match(IDENT);
					_localctx._names.Add(_localctx._IDENT);
					}
					} 
				}
				State = 264;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,18,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprValueContext : ParserRuleContext {
		public IToken integerValue;
		public IToken floatValue;
		public IToken boolValue;
		public IToken stringValue;
		public ITerminalNode INTEGER() { return GetToken(TemplateParser.INTEGER, 0); }
		public ITerminalNode FLOAT() { return GetToken(TemplateParser.FLOAT, 0); }
		public ITerminalNode BOOL() { return GetToken(TemplateParser.BOOL, 0); }
		public ITerminalNode STRING() { return GetToken(TemplateParser.STRING, 0); }
		public ExprValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_exprValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterExprValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitExprValue(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExprValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprValueContext exprValue() {
		ExprValueContext _localctx = new ExprValueContext(Context, State);
		EnterRule(_localctx, 24, RULE_exprValue);
		try {
			State = 269;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INTEGER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 265; _localctx.integerValue = Match(INTEGER);
				}
				break;
			case FLOAT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 266; _localctx.floatValue = Match(FLOAT);
				}
				break;
			case BOOL:
				EnterOuterAlt(_localctx, 3);
				{
				State = 267; _localctx.boolValue = Match(BOOL);
				}
				break;
			case STRING:
				EnterOuterAlt(_localctx, 4);
				{
				State = 268; _localctx.stringValue = Match(STRING);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 9: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 19);
		case 1: return Precpred(Context, 18);
		case 2: return Precpred(Context, 17);
		case 3: return Precpred(Context, 16);
		case 4: return Precpred(Context, 15);
		case 5: return Precpred(Context, 14);
		case 6: return Precpred(Context, 13);
		case 7: return Precpred(Context, 12);
		case 8: return Precpred(Context, 11);
		case 9: return Precpred(Context, 10);
		case 10: return Precpred(Context, 9);
		case 11: return Precpred(Context, 8);
		case 12: return Precpred(Context, 7);
		case 13: return Precpred(Context, 6);
		case 14: return Precpred(Context, 5);
		case 15: return Precpred(Context, 4);
		case 16: return Precpred(Context, 3);
		case 17: return Precpred(Context, 2);
		case 18: return Precpred(Context, 24);
		case 19: return Precpred(Context, 22);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x41', '\x112', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x3', '\x2', '\a', '\x2', '\x1E', '\n', '\x2', '\f', '\x2', '\xE', 
		'\x2', '!', '\v', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', '/', '\n', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x5', 
		'\x4', '\x35', '\n', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\a', '\x5', '?', '\n', '\x5', '\f', '\x5', '\xE', '\x5', '\x42', '\v', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', 'P', '\n', '\x6', '\a', 
		'\x6', 'R', '\n', '\x6', '\f', '\x6', '\xE', '\x6', 'U', '\v', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\a', '\a', '_', '\n', '\a', '\f', '\a', 
		'\xE', '\a', '\x62', '\v', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\a', '\b', 'i', '\n', '\b', '\f', '\b', '\xE', 
		'\b', 'l', '\v', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', 
		'\t', 'w', '\n', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', '{', '\n', 
		'\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', '\x7F', '\n', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\a', '\t', '\x84', '\n', '\t', '\f', 
		'\t', '\xE', '\t', '\x87', '\v', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\a', '\n', '\x93', '\n', '\n', '\f', '\n', 
		'\xE', '\n', '\x96', '\v', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x5', '\v', 
		'\xB0', '\n', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\a', '\v', 
		'\xEC', '\n', '\v', '\f', '\v', '\xE', '\v', '\xEF', '\v', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\a', '\f', '\xF4', '\n', '\f', '\f', 
		'\f', '\xE', '\f', '\xF7', '\v', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\a', '\f', '\xFD', '\n', '\f', '\f', '\f', '\xE', 
		'\f', '\x100', '\v', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\a', '\r', '\x107', '\n', '\r', '\f', '\r', '\xE', 
		'\r', '\x10A', '\v', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x5', '\xE', '\x110', '\n', '\xE', '\x3', '\xE', '\x2', '\x3', 
		'\x14', '\xF', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', 
		'\x14', '\x16', '\x18', '\x1A', '\x2', '\x2', '\x2', '\x13E', '\x2', '\x1F', 
		'\x3', '\x2', '\x2', '\x2', '\x4', '.', '\x3', '\x2', '\x2', '\x2', '\x6', 
		'\x30', '\x3', '\x2', '\x2', '\x2', '\b', '\x38', '\x3', '\x2', '\x2', 
		'\x2', '\n', '\x45', '\x3', '\x2', '\x2', '\x2', '\f', 'X', '\x3', '\x2', 
		'\x2', '\x2', '\xE', '\x65', '\x3', '\x2', '\x2', '\x2', '\x10', 's', 
		'\x3', '\x2', '\x2', '\x2', '\x12', '\x8A', '\x3', '\x2', '\x2', '\x2', 
		'\x14', '\xAF', '\x3', '\x2', '\x2', '\x2', '\x16', '\xF0', '\x3', '\x2', 
		'\x2', '\x2', '\x18', '\x103', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x10F', 
		'\x3', '\x2', '\x2', '\x2', '\x1C', '\x1E', '\x5', '\x4', '\x3', '\x2', 
		'\x1D', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x1E', '!', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x1F', ' ', 
		'\x3', '\x2', '\x2', '\x2', ' ', '\x3', '\x3', '\x2', '\x2', '\x2', '!', 
		'\x1F', '\x3', '\x2', '\x2', '\x2', '\"', '/', '\x5', '\x6', '\x4', '\x2', 
		'#', '/', '\x5', '\b', '\x5', '\x2', '$', '/', '\x5', '\n', '\x6', '\x2', 
		'%', '/', '\x5', '\f', '\a', '\x2', '&', '/', '\x5', '\xE', '\b', '\x2', 
		'\'', '/', '\x5', '\x10', '\t', '\x2', '(', '/', '\x5', '\x12', '\n', 
		'\x2', ')', '/', '\x5', '\x14', '\v', '\x2', '*', '/', '\a', '\x4', '\x2', 
		'\x2', '+', '/', '\a', '<', '\x2', '\x2', ',', '/', '\a', '=', '\x2', 
		'\x2', '-', '/', '\a', '>', '\x2', '\x2', '.', '\"', '\x3', '\x2', '\x2', 
		'\x2', '.', '#', '\x3', '\x2', '\x2', '\x2', '.', '$', '\x3', '\x2', '\x2', 
		'\x2', '.', '%', '\x3', '\x2', '\x2', '\x2', '.', '&', '\x3', '\x2', '\x2', 
		'\x2', '.', '\'', '\x3', '\x2', '\x2', '\x2', '.', '(', '\x3', '\x2', 
		'\x2', '\x2', '.', ')', '\x3', '\x2', '\x2', '\x2', '.', '*', '\x3', '\x2', 
		'\x2', '\x2', '.', '+', '\x3', '\x2', '\x2', '\x2', '.', ',', '\x3', '\x2', 
		'\x2', '\x2', '.', '-', '\x3', '\x2', '\x2', '\x2', '/', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x30', '\x31', '\a', '\x33', '\x2', '\x2', '\x31', 
		'\x34', '\a', '?', '\x2', '\x2', '\x32', '\x33', '\a', '*', '\x2', '\x2', 
		'\x33', '\x35', '\x5', '\x14', '\v', '\x2', '\x34', '\x32', '\x3', '\x2', 
		'\x2', '\x2', '\x34', '\x35', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', 
		'\x3', '\x2', '\x2', '\x2', '\x36', '\x37', '\a', '\x32', '\x2', '\x2', 
		'\x37', '\a', '\x3', '\x2', '\x2', '\x2', '\x38', '\x39', '\a', '\x34', 
		'\x2', '\x2', '\x39', ':', '\a', '\x1D', '\x2', '\x2', ':', ';', '\x5', 
		'\x14', '\v', '\x2', ';', '<', '\a', '\x1E', '\x2', '\x2', '<', '@', '\a', 
		'\x14', '\x2', '\x2', '=', '?', '\x5', '\x4', '\x3', '\x2', '>', '=', 
		'\x3', '\x2', '\x2', '\x2', '?', '\x42', '\x3', '\x2', '\x2', '\x2', '@', 
		'>', '\x3', '\x2', '\x2', '\x2', '@', '\x41', '\x3', '\x2', '\x2', '\x2', 
		'\x41', '\x43', '\x3', '\x2', '\x2', '\x2', '\x42', '@', '\x3', '\x2', 
		'\x2', '\x2', '\x43', '\x44', '\a', '\x15', '\x2', '\x2', '\x44', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\a', '\x35', '\x2', '\x2', 
		'\x46', 'G', '\a', '\x1D', '\x2', '\x2', 'G', 'H', '\x5', '\x14', '\v', 
		'\x2', 'H', 'I', '\a', '\x1E', '\x2', '\x2', 'I', 'S', '\a', '\x14', '\x2', 
		'\x2', 'J', 'K', '\a', '\x36', '\x2', '\x2', 'K', 'L', '\x5', '\x14', 
		'\v', '\x2', 'L', 'M', '\a', '\x31', '\x2', '\x2', 'M', 'O', '\x5', '\x14', 
		'\v', '\x2', 'N', 'P', '\a', '<', '\x2', '\x2', 'O', 'N', '\x3', '\x2', 
		'\x2', '\x2', 'O', 'P', '\x3', '\x2', '\x2', '\x2', 'P', 'R', '\x3', '\x2', 
		'\x2', '\x2', 'Q', 'J', '\x3', '\x2', '\x2', '\x2', 'R', 'U', '\x3', '\x2', 
		'\x2', '\x2', 'S', 'Q', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\x3', '\x2', 
		'\x2', '\x2', 'T', 'V', '\x3', '\x2', '\x2', '\x2', 'U', 'S', '\x3', '\x2', 
		'\x2', '\x2', 'V', 'W', '\a', '\x15', '\x2', '\x2', 'W', '\v', '\x3', 
		'\x2', '\x2', '\x2', 'X', 'Y', '\a', '\x37', '\x2', '\x2', 'Y', 'Z', '\a', 
		'\x1D', '\x2', '\x2', 'Z', '[', '\x5', '\x14', '\v', '\x2', '[', '\\', 
		'\a', '\x1E', '\x2', '\x2', '\\', '`', '\a', '\x14', '\x2', '\x2', ']', 
		'_', '\x5', '\x4', '\x3', '\x2', '^', ']', '\x3', '\x2', '\x2', '\x2', 
		'_', '\x62', '\x3', '\x2', '\x2', '\x2', '`', '^', '\x3', '\x2', '\x2', 
		'\x2', '`', '\x61', '\x3', '\x2', '\x2', '\x2', '\x61', '\x63', '\x3', 
		'\x2', '\x2', '\x2', '\x62', '`', '\x3', '\x2', '\x2', '\x2', '\x63', 
		'\x64', '\a', '\x15', '\x2', '\x2', '\x64', '\r', '\x3', '\x2', '\x2', 
		'\x2', '\x65', '\x66', '\a', '\x38', '\x2', '\x2', '\x66', 'j', '\a', 
		'\x14', '\x2', '\x2', 'g', 'i', '\x5', '\x4', '\x3', '\x2', 'h', 'g', 
		'\x3', '\x2', '\x2', '\x2', 'i', 'l', '\x3', '\x2', '\x2', '\x2', 'j', 
		'h', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\x3', '\x2', '\x2', '\x2', 
		'k', 'm', '\x3', '\x2', '\x2', '\x2', 'l', 'j', '\x3', '\x2', '\x2', '\x2', 
		'm', 'n', '\a', '\x15', '\x2', '\x2', 'n', 'o', '\a', '\x37', '\x2', '\x2', 
		'o', 'p', '\a', '\x1D', '\x2', '\x2', 'p', 'q', '\x5', '\x14', '\v', '\x2', 
		'q', 'r', '\a', '\x1E', '\x2', '\x2', 'r', '\xF', '\x3', '\x2', '\x2', 
		'\x2', 's', 't', '\a', '\x39', '\x2', '\x2', 't', 'v', '\a', '\x1D', '\x2', 
		'\x2', 'u', 'w', '\x5', '\x4', '\x3', '\x2', 'v', 'u', '\x3', '\x2', '\x2', 
		'\x2', 'v', 'w', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\x3', '\x2', '\x2', 
		'\x2', 'x', 'z', '\a', '\x32', '\x2', '\x2', 'y', '{', '\x5', '\x4', '\x3', 
		'\x2', 'z', 'y', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\x3', '\x2', '\x2', 
		'\x2', '{', '|', '\x3', '\x2', '\x2', '\x2', '|', '~', '\a', '\x32', '\x2', 
		'\x2', '}', '\x7F', '\x5', '\x4', '\x3', '\x2', '~', '}', '\x3', '\x2', 
		'\x2', '\x2', '~', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', 
		'\x3', '\x2', '\x2', '\x2', '\x80', '\x81', '\a', '\x1E', '\x2', '\x2', 
		'\x81', '\x85', '\a', '\x14', '\x2', '\x2', '\x82', '\x84', '\x5', '\x4', 
		'\x3', '\x2', '\x83', '\x82', '\x3', '\x2', '\x2', '\x2', '\x84', '\x87', 
		'\x3', '\x2', '\x2', '\x2', '\x85', '\x83', '\x3', '\x2', '\x2', '\x2', 
		'\x85', '\x86', '\x3', '\x2', '\x2', '\x2', '\x86', '\x88', '\x3', '\x2', 
		'\x2', '\x2', '\x87', '\x85', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', 
		'\a', '\x15', '\x2', '\x2', '\x89', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x8A', '\x8B', '\a', ':', '\x2', '\x2', '\x8B', '\x8C', '\a', '\x1D', 
		'\x2', '\x2', '\x8C', '\x8D', '\x5', '\x4', '\x3', '\x2', '\x8D', '\x8E', 
		'\a', ';', '\x2', '\x2', '\x8E', '\x8F', '\x5', '\x4', '\x3', '\x2', '\x8F', 
		'\x90', '\a', '\x1E', '\x2', '\x2', '\x90', '\x94', '\a', '\x14', '\x2', 
		'\x2', '\x91', '\x93', '\x5', '\x4', '\x3', '\x2', '\x92', '\x91', '\x3', 
		'\x2', '\x2', '\x2', '\x93', '\x96', '\x3', '\x2', '\x2', '\x2', '\x94', 
		'\x92', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\x3', '\x2', '\x2', 
		'\x2', '\x95', '\x97', '\x3', '\x2', '\x2', '\x2', '\x96', '\x94', '\x3', 
		'\x2', '\x2', '\x2', '\x97', '\x98', '\a', '\x15', '\x2', '\x2', '\x98', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\b', '\v', '\x1', 
		'\x2', '\x9A', '\x9B', '\a', '\x1D', '\x2', '\x2', '\x9B', '\x9C', '\x5', 
		'\x14', '\v', '\x2', '\x9C', '\x9D', '\a', '\x1E', '\x2', '\x2', '\x9D', 
		'\xB0', '\x3', '\x2', '\x2', '\x2', '\x9E', '\xB0', '\x5', '\x16', '\f', 
		'\x2', '\x9F', '\xB0', '\x5', '\x18', '\r', '\x2', '\xA0', '\xA1', '\a', 
		'\x1C', '\x2', '\x2', '\xA1', '\xB0', '\x5', '\x14', '\v', '\x1D', '\xA2', 
		'\xA3', '\a', '\x1D', '\x2', '\x2', '\xA3', '\xA4', '\a', '?', '\x2', 
		'\x2', '\xA4', '\xA5', '\a', '\x1E', '\x2', '\x2', '\xA5', '\xB0', '\x5', 
		'\x14', '\v', '\x1C', '\xA6', '\xA7', '\a', '\x16', '\x2', '\x2', '\xA7', 
		'\xB0', '\x5', '\x14', '\v', '\x1B', '\xA8', '\xA9', '\a', '\x17', '\x2', 
		'\x2', '\xA9', '\xB0', '\x5', '\x14', '\v', '\x19', '\xAA', '\xAB', '\a', 
		'\"', '\x2', '\x2', '\xAB', '\xB0', '\x5', '\x14', '\v', '\x17', '\xAC', 
		'\xAD', '\a', '#', '\x2', '\x2', '\xAD', '\xB0', '\x5', '\x14', '\v', 
		'\x16', '\xAE', '\xB0', '\x5', '\x1A', '\xE', '\x2', '\xAF', '\x99', '\x3', 
		'\x2', '\x2', '\x2', '\xAF', '\x9E', '\x3', '\x2', '\x2', '\x2', '\xAF', 
		'\x9F', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xA0', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xA6', '\x3', 
		'\x2', '\x2', '\x2', '\xAF', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xAF', 
		'\xAA', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xAC', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xED', '\x3', 
		'\x2', '\x2', '\x2', '\xB1', '\xB2', '\f', '\x15', '\x2', '\x2', '\xB2', 
		'\xB3', '\a', '\x18', '\x2', '\x2', '\xB3', '\xEC', '\x5', '\x14', '\v', 
		'\x16', '\xB4', '\xB5', '\f', '\x14', '\x2', '\x2', '\xB5', '\xB6', '\a', 
		'\x19', '\x2', '\x2', '\xB6', '\xEC', '\x5', '\x14', '\v', '\x15', '\xB7', 
		'\xB8', '\f', '\x13', '\x2', '\x2', '\xB8', '\xB9', '\a', '\x1A', '\x2', 
		'\x2', '\xB9', '\xEC', '\x5', '\x14', '\v', '\x14', '\xBA', '\xBB', '\f', 
		'\x12', '\x2', '\x2', '\xBB', '\xBC', '\a', '\x1B', '\x2', '\x2', '\xBC', 
		'\xEC', '\x5', '\x14', '\v', '\x13', '\xBD', '\xBE', '\f', '\x11', '\x2', 
		'\x2', '\xBE', '\xBF', '\a', '\x1C', '\x2', '\x2', '\xBF', '\xEC', '\x5', 
		'\x14', '\v', '\x12', '\xC0', '\xC1', '\f', '\x10', '\x2', '\x2', '\xC1', 
		'\xC2', '\a', '$', '\x2', '\x2', '\xC2', '\xEC', '\x5', '\x14', '\v', 
		'\x11', '\xC3', '\xC4', '\f', '\xF', '\x2', '\x2', '\xC4', '\xC5', '\a', 
		'%', '\x2', '\x2', '\xC5', '\xEC', '\x5', '\x14', '\v', '\x10', '\xC6', 
		'\xC7', '\f', '\xE', '\x2', '\x2', '\xC7', '\xC8', '\a', '&', '\x2', '\x2', 
		'\xC8', '\xEC', '\x5', '\x14', '\v', '\xF', '\xC9', '\xCA', '\f', '\r', 
		'\x2', '\x2', '\xCA', '\xCB', '\a', '\'', '\x2', '\x2', '\xCB', '\xEC', 
		'\x5', '\x14', '\v', '\xE', '\xCC', '\xCD', '\f', '\f', '\x2', '\x2', 
		'\xCD', '\xCE', '\a', '(', '\x2', '\x2', '\xCE', '\xEC', '\x5', '\x14', 
		'\v', '\r', '\xCF', '\xD0', '\f', '\v', '\x2', '\x2', '\xD0', '\xD1', 
		'\a', ')', '\x2', '\x2', '\xD1', '\xEC', '\x5', '\x14', '\v', '\f', '\xD2', 
		'\xD3', '\f', '\n', '\x2', '\x2', '\xD3', '\xD4', '\a', '*', '\x2', '\x2', 
		'\xD4', '\xEC', '\x5', '\x14', '\v', '\v', '\xD5', '\xD6', '\f', '\t', 
		'\x2', '\x2', '\xD6', '\xD7', '\a', '!', '\x2', '\x2', '\xD7', '\xEC', 
		'\x5', '\x14', '\v', '\n', '\xD8', '\xD9', '\f', '\b', '\x2', '\x2', '\xD9', 
		'\xDA', '\a', '-', '\x2', '\x2', '\xDA', '\xEC', '\x5', '\x14', '\v', 
		'\t', '\xDB', '\xDC', '\f', '\a', '\x2', '\x2', '\xDC', '\xDD', '\a', 
		'/', '\x2', '\x2', '\xDD', '\xEC', '\x5', '\x14', '\v', '\b', '\xDE', 
		'\xDF', '\f', '\x6', '\x2', '\x2', '\xDF', '\xE0', '\a', '.', '\x2', '\x2', 
		'\xE0', '\xEC', '\x5', '\x14', '\v', '\a', '\xE1', '\xE2', '\f', '\x5', 
		'\x2', '\x2', '\xE2', '\xE3', '\a', '+', '\x2', '\x2', '\xE3', '\xEC', 
		'\x5', '\x14', '\v', '\x6', '\xE4', '\xE5', '\f', '\x4', '\x2', '\x2', 
		'\xE5', '\xE6', '\a', ',', '\x2', '\x2', '\xE6', '\xEC', '\x5', '\x14', 
		'\v', '\x5', '\xE7', '\xE8', '\f', '\x1A', '\x2', '\x2', '\xE8', '\xEC', 
		'\a', '\x16', '\x2', '\x2', '\xE9', '\xEA', '\f', '\x18', '\x2', '\x2', 
		'\xEA', '\xEC', '\a', '\x17', '\x2', '\x2', '\xEB', '\xB1', '\x3', '\x2', 
		'\x2', '\x2', '\xEB', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xB7', 
		'\x3', '\x2', '\x2', '\x2', '\xEB', '\xBA', '\x3', '\x2', '\x2', '\x2', 
		'\xEB', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xC0', '\x3', '\x2', 
		'\x2', '\x2', '\xEB', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xC6', 
		'\x3', '\x2', '\x2', '\x2', '\xEB', '\xC9', '\x3', '\x2', '\x2', '\x2', 
		'\xEB', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xCF', '\x3', '\x2', 
		'\x2', '\x2', '\xEB', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xD5', 
		'\x3', '\x2', '\x2', '\x2', '\xEB', '\xD8', '\x3', '\x2', '\x2', '\x2', 
		'\xEB', '\xDB', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xDE', '\x3', '\x2', 
		'\x2', '\x2', '\xEB', '\xE1', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xE4', 
		'\x3', '\x2', '\x2', '\x2', '\xEB', '\xE7', '\x3', '\x2', '\x2', '\x2', 
		'\xEB', '\xE9', '\x3', '\x2', '\x2', '\x2', '\xEC', '\xEF', '\x3', '\x2', 
		'\x2', '\x2', '\xED', '\xEB', '\x3', '\x2', '\x2', '\x2', '\xED', '\xEE', 
		'\x3', '\x2', '\x2', '\x2', '\xEE', '\x15', '\x3', '\x2', '\x2', '\x2', 
		'\xEF', '\xED', '\x3', '\x2', '\x2', '\x2', '\xF0', '\xF5', '\a', '?', 
		'\x2', '\x2', '\xF1', '\xF2', '\a', '\x1F', '\x2', '\x2', '\xF2', '\xF4', 
		'\a', '?', '\x2', '\x2', '\xF3', '\xF1', '\x3', '\x2', '\x2', '\x2', '\xF4', 
		'\xF7', '\x3', '\x2', '\x2', '\x2', '\xF5', '\xF3', '\x3', '\x2', '\x2', 
		'\x2', '\xF5', '\xF6', '\x3', '\x2', '\x2', '\x2', '\xF6', '\xF8', '\x3', 
		'\x2', '\x2', '\x2', '\xF7', '\xF5', '\x3', '\x2', '\x2', '\x2', '\xF8', 
		'\xF9', '\a', '\x1D', '\x2', '\x2', '\xF9', '\xFE', '\x5', '\x14', '\v', 
		'\x2', '\xFA', '\xFB', '\a', ' ', '\x2', '\x2', '\xFB', '\xFD', '\x5', 
		'\x14', '\v', '\x2', '\xFC', '\xFA', '\x3', '\x2', '\x2', '\x2', '\xFD', 
		'\x100', '\x3', '\x2', '\x2', '\x2', '\xFE', '\xFC', '\x3', '\x2', '\x2', 
		'\x2', '\xFE', '\xFF', '\x3', '\x2', '\x2', '\x2', '\xFF', '\x101', '\x3', 
		'\x2', '\x2', '\x2', '\x100', '\xFE', '\x3', '\x2', '\x2', '\x2', '\x101', 
		'\x102', '\a', '\x1E', '\x2', '\x2', '\x102', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x103', '\x108', '\a', '?', '\x2', '\x2', '\x104', '\x105', '\a', 
		'\x1F', '\x2', '\x2', '\x105', '\x107', '\a', '?', '\x2', '\x2', '\x106', 
		'\x104', '\x3', '\x2', '\x2', '\x2', '\x107', '\x10A', '\x3', '\x2', '\x2', 
		'\x2', '\x108', '\x106', '\x3', '\x2', '\x2', '\x2', '\x108', '\x109', 
		'\x3', '\x2', '\x2', '\x2', '\x109', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x10A', '\x108', '\x3', '\x2', '\x2', '\x2', '\x10B', '\x110', '\a', 
		'\x6', '\x2', '\x2', '\x10C', '\x110', '\a', '\a', '\x2', '\x2', '\x10D', 
		'\x110', '\a', '\b', '\x2', '\x2', '\x10E', '\x110', '\a', '\x13', '\x2', 
		'\x2', '\x10F', '\x10B', '\x3', '\x2', '\x2', '\x2', '\x10F', '\x10C', 
		'\x3', '\x2', '\x2', '\x2', '\x10F', '\x10D', '\x3', '\x2', '\x2', '\x2', 
		'\x10F', '\x10E', '\x3', '\x2', '\x2', '\x2', '\x110', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x16', '\x1F', '.', '\x34', '@', 'O', 'S', '`', 
		'j', 'v', 'z', '~', '\x85', '\x94', '\xAF', '\xEB', '\xED', '\xF5', '\xFE', 
		'\x108', '\x10F',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
