//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from TemplateParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class TemplateParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		OPEN=1, TEXT=2, CLOSE=3, INTEGER=4, FLOAT=5, BOOL=6, SET_DIV=7, SET_MUL=8, 
		SET_MOD=9, SET_ADD=10, SET_SUB=11, SET_SHIFTL=12, SET_SHIFTR=13, SET_BIT_AND=14, 
		SET_BIT_XOR=15, SET_BIT_OR=16, STRING=17, BRACE_L=18, BRACE_R=19, INCREMENT=20, 
		DECREMENT=21, MUL=22, DIV=23, MOD=24, ADD=25, SUB=26, PARENTHESES_L=27, 
		PARENTHESES_R=28, DOT=29, COMMA=30, NOTEQUAL=31, LOGIC_NOT=32, BIT_INVERT=33, 
		SHIFTL=34, SHIFTR=35, LESS=36, LESSEQUAL=37, GREATER=38, GREATEREQUAL=39, 
		EQUAL=40, LOGIC_AND=41, LOGIC_OR=42, BIT_AND=43, BIT_OR=44, BIT_XOR=45, 
		SET=46, COLON=47, SEMICOLON=48, VAR=49, IF=50, SWITCH=51, CASE=52, WHILE=53, 
		DO=54, FOR=55, FOREACH=56, IN=57, BREAK=58, CONTINUE=59, RETURN=60, IDENT=61, 
		COMMENT=62, WS=63;
	public const int
		RULE_document = 0, RULE_code = 1, RULE_text = 2, RULE_var = 3, RULE_if = 4, 
		RULE_switch = 5, RULE_while = 6, RULE_dowhile = 7, RULE_for = 8, RULE_foreach = 9, 
		RULE_expr = 10, RULE_exprCall = 11, RULE_exprProp = 12, RULE_exprValue = 13;
	public static readonly string[] ruleNames = {
		"document", "code", "text", "var", "if", "switch", "while", "dowhile", 
		"for", "foreach", "expr", "exprCall", "exprProp", "exprValue"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, "'/='", "'*='", "'%='", "'+='", 
		"'-='", "'<<='", "'>>='", "'&='", "'^='", "'|='", null, "'{'", "'}'", 
		"'++'", "'--'", "'*'", "'/'", "'%'", "'+'", "'-'", "'('", "')'", "'.'", 
		"','", "'!='", "'!'", "'~'", "'<<'", "'>>'", "'<'", "'<='", "'>'", "'>='", 
		"'=='", "'&&'", "'||'", "'&'", "'|'", "'^'", "'='", "':'", "';'", "'var'", 
		"'if'", "'switch'", "'case'", "'while'", "'do'", "'for'", "'foreach'", 
		"'in'", "'break'", "'continue'", "'return'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "OPEN", "TEXT", "CLOSE", "INTEGER", "FLOAT", "BOOL", "SET_DIV", 
		"SET_MUL", "SET_MOD", "SET_ADD", "SET_SUB", "SET_SHIFTL", "SET_SHIFTR", 
		"SET_BIT_AND", "SET_BIT_XOR", "SET_BIT_OR", "STRING", "BRACE_L", "BRACE_R", 
		"INCREMENT", "DECREMENT", "MUL", "DIV", "MOD", "ADD", "SUB", "PARENTHESES_L", 
		"PARENTHESES_R", "DOT", "COMMA", "NOTEQUAL", "LOGIC_NOT", "BIT_INVERT", 
		"SHIFTL", "SHIFTR", "LESS", "LESSEQUAL", "GREATER", "GREATEREQUAL", "EQUAL", 
		"LOGIC_AND", "LOGIC_OR", "BIT_AND", "BIT_OR", "BIT_XOR", "SET", "COLON", 
		"SEMICOLON", "VAR", "IF", "SWITCH", "CASE", "WHILE", "DO", "FOR", "FOREACH", 
		"IN", "BREAK", "CONTINUE", "RETURN", "IDENT", "COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "TemplateParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static TemplateParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public TemplateParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public TemplateParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class DocumentContext : ParserRuleContext {
		public CodeContext[] code() {
			return GetRuleContexts<CodeContext>();
		}
		public CodeContext code(int i) {
			return GetRuleContext<CodeContext>(i);
		}
		public DocumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_document; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterDocument(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitDocument(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDocument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DocumentContext document() {
		DocumentContext _localctx = new DocumentContext(Context, State);
		EnterRule(_localctx, 0, RULE_document);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 31;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TEXT) | (1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << VAR) | (1L << IF) | (1L << SWITCH) | (1L << WHILE) | (1L << DO) | (1L << FOR) | (1L << FOREACH) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << IDENT))) != 0)) {
				{
				{
				State = 28; code();
				}
				}
				State = 33;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CodeContext : ParserRuleContext {
		public VarContext var() {
			return GetRuleContext<VarContext>(0);
		}
		public IfContext @if() {
			return GetRuleContext<IfContext>(0);
		}
		public SwitchContext @switch() {
			return GetRuleContext<SwitchContext>(0);
		}
		public WhileContext @while() {
			return GetRuleContext<WhileContext>(0);
		}
		public DowhileContext dowhile() {
			return GetRuleContext<DowhileContext>(0);
		}
		public ForContext @for() {
			return GetRuleContext<ForContext>(0);
		}
		public ForeachContext @foreach() {
			return GetRuleContext<ForeachContext>(0);
		}
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public TextContext text() {
			return GetRuleContext<TextContext>(0);
		}
		public ITerminalNode BREAK() { return GetToken(TemplateParser.BREAK, 0); }
		public ITerminalNode CONTINUE() { return GetToken(TemplateParser.CONTINUE, 0); }
		public ITerminalNode RETURN() { return GetToken(TemplateParser.RETURN, 0); }
		public CodeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_code; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterCode(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitCode(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCode(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CodeContext code() {
		CodeContext _localctx = new CodeContext(Context, State);
		EnterRule(_localctx, 2, RULE_code);
		try {
			State = 46;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case VAR:
				EnterOuterAlt(_localctx, 1);
				{
				State = 34; var();
				}
				break;
			case IF:
				EnterOuterAlt(_localctx, 2);
				{
				State = 35; @if();
				}
				break;
			case SWITCH:
				EnterOuterAlt(_localctx, 3);
				{
				State = 36; @switch();
				}
				break;
			case WHILE:
				EnterOuterAlt(_localctx, 4);
				{
				State = 37; @while();
				}
				break;
			case DO:
				EnterOuterAlt(_localctx, 5);
				{
				State = 38; dowhile();
				}
				break;
			case FOR:
				EnterOuterAlt(_localctx, 6);
				{
				State = 39; @for();
				}
				break;
			case FOREACH:
				EnterOuterAlt(_localctx, 7);
				{
				State = 40; @foreach();
				}
				break;
			case INTEGER:
			case FLOAT:
			case BOOL:
			case STRING:
			case INCREMENT:
			case DECREMENT:
			case SUB:
			case PARENTHESES_L:
			case LOGIC_NOT:
			case BIT_INVERT:
			case IDENT:
				EnterOuterAlt(_localctx, 8);
				{
				State = 41; expr(0);
				}
				break;
			case TEXT:
				EnterOuterAlt(_localctx, 9);
				{
				State = 42; text();
				}
				break;
			case BREAK:
				EnterOuterAlt(_localctx, 10);
				{
				State = 43; Match(BREAK);
				}
				break;
			case CONTINUE:
				EnterOuterAlt(_localctx, 11);
				{
				State = 44; Match(CONTINUE);
				}
				break;
			case RETURN:
				EnterOuterAlt(_localctx, 12);
				{
				State = 45; Match(RETURN);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextContext : ParserRuleContext {
		public ITerminalNode TEXT() { return GetToken(TemplateParser.TEXT, 0); }
		public TextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_text; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterText(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitText(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitText(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TextContext text() {
		TextContext _localctx = new TextContext(Context, State);
		EnterRule(_localctx, 4, RULE_text);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 48; Match(TEXT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VarContext : ParserRuleContext {
		public IToken keyword;
		public IToken key;
		public ITerminalNode SEMICOLON() { return GetToken(TemplateParser.SEMICOLON, 0); }
		public ITerminalNode VAR() { return GetToken(TemplateParser.VAR, 0); }
		public ITerminalNode IDENT() { return GetToken(TemplateParser.IDENT, 0); }
		public ITerminalNode EQUAL() { return GetToken(TemplateParser.EQUAL, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public VarContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterVar(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitVar(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VarContext var() {
		VarContext _localctx = new VarContext(Context, State);
		EnterRule(_localctx, 6, RULE_var);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 50; _localctx.keyword = Match(VAR);
			State = 51; _localctx.key = Match(IDENT);
			State = 54;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==EQUAL) {
				{
				State = 52; Match(EQUAL);
				State = 53; expr(0);
				}
			}

			State = 56; Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IfContext : ParserRuleContext {
		public IToken keyword;
		public ExprContext condition;
		public ITerminalNode PARENTHESES_L() { return GetToken(TemplateParser.PARENTHESES_L, 0); }
		public ITerminalNode PARENTHESES_R() { return GetToken(TemplateParser.PARENTHESES_R, 0); }
		public ITerminalNode BRACE_L() { return GetToken(TemplateParser.BRACE_L, 0); }
		public ITerminalNode BRACE_R() { return GetToken(TemplateParser.BRACE_R, 0); }
		public ITerminalNode IF() { return GetToken(TemplateParser.IF, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public CodeContext[] code() {
			return GetRuleContexts<CodeContext>();
		}
		public CodeContext code(int i) {
			return GetRuleContext<CodeContext>(i);
		}
		public IfContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_if; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterIf(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitIf(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIf(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IfContext @if() {
		IfContext _localctx = new IfContext(Context, State);
		EnterRule(_localctx, 8, RULE_if);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 58; _localctx.keyword = Match(IF);
			State = 59; Match(PARENTHESES_L);
			State = 60; _localctx.condition = expr(0);
			State = 61; Match(PARENTHESES_R);
			State = 62; Match(BRACE_L);
			State = 66;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TEXT) | (1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << VAR) | (1L << IF) | (1L << SWITCH) | (1L << WHILE) | (1L << DO) | (1L << FOR) | (1L << FOREACH) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << IDENT))) != 0)) {
				{
				{
				State = 63; code();
				}
				}
				State = 68;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 69; Match(BRACE_R);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SwitchContext : ParserRuleContext {
		public IToken keywordA;
		public ExprContext condition;
		public IToken _CASE;
		public IList<IToken> _keywordB = new List<IToken>();
		public ITerminalNode PARENTHESES_L() { return GetToken(TemplateParser.PARENTHESES_L, 0); }
		public ITerminalNode PARENTHESES_R() { return GetToken(TemplateParser.PARENTHESES_R, 0); }
		public ITerminalNode BRACE_L() { return GetToken(TemplateParser.BRACE_L, 0); }
		public ITerminalNode BRACE_R() { return GetToken(TemplateParser.BRACE_R, 0); }
		public ITerminalNode SWITCH() { return GetToken(TemplateParser.SWITCH, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode[] COLON() { return GetTokens(TemplateParser.COLON); }
		public ITerminalNode COLON(int i) {
			return GetToken(TemplateParser.COLON, i);
		}
		public ITerminalNode[] CASE() { return GetTokens(TemplateParser.CASE); }
		public ITerminalNode CASE(int i) {
			return GetToken(TemplateParser.CASE, i);
		}
		public ITerminalNode[] BREAK() { return GetTokens(TemplateParser.BREAK); }
		public ITerminalNode BREAK(int i) {
			return GetToken(TemplateParser.BREAK, i);
		}
		public SwitchContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_switch; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterSwitch(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitSwitch(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSwitch(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SwitchContext @switch() {
		SwitchContext _localctx = new SwitchContext(Context, State);
		EnterRule(_localctx, 10, RULE_switch);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 71; _localctx.keywordA = Match(SWITCH);
			State = 72; Match(PARENTHESES_L);
			State = 73; _localctx.condition = expr(0);
			State = 74; Match(PARENTHESES_R);
			State = 75; Match(BRACE_L);
			State = 85;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==CASE) {
				{
				{
				State = 76; _localctx._CASE = Match(CASE);
				_localctx._keywordB.Add(_localctx._CASE);
				State = 77; expr(0);
				State = 78; Match(COLON);
				State = 79; expr(0);
				State = 81;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==BREAK) {
					{
					State = 80; Match(BREAK);
					}
				}

				}
				}
				State = 87;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 88; Match(BRACE_R);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WhileContext : ParserRuleContext {
		public IToken keyword;
		public ExprContext condition;
		public ITerminalNode PARENTHESES_L() { return GetToken(TemplateParser.PARENTHESES_L, 0); }
		public ITerminalNode PARENTHESES_R() { return GetToken(TemplateParser.PARENTHESES_R, 0); }
		public ITerminalNode BRACE_L() { return GetToken(TemplateParser.BRACE_L, 0); }
		public ITerminalNode BRACE_R() { return GetToken(TemplateParser.BRACE_R, 0); }
		public ITerminalNode WHILE() { return GetToken(TemplateParser.WHILE, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public CodeContext[] code() {
			return GetRuleContexts<CodeContext>();
		}
		public CodeContext code(int i) {
			return GetRuleContext<CodeContext>(i);
		}
		public WhileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_while; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterWhile(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitWhile(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhile(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public WhileContext @while() {
		WhileContext _localctx = new WhileContext(Context, State);
		EnterRule(_localctx, 12, RULE_while);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 90; _localctx.keyword = Match(WHILE);
			State = 91; Match(PARENTHESES_L);
			State = 92; _localctx.condition = expr(0);
			State = 93; Match(PARENTHESES_R);
			State = 94; Match(BRACE_L);
			State = 98;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TEXT) | (1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << VAR) | (1L << IF) | (1L << SWITCH) | (1L << WHILE) | (1L << DO) | (1L << FOR) | (1L << FOREACH) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << IDENT))) != 0)) {
				{
				{
				State = 95; code();
				}
				}
				State = 100;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 101; Match(BRACE_R);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DowhileContext : ParserRuleContext {
		public IToken keywordA;
		public IToken keywordB;
		public ExprContext condition;
		public ITerminalNode BRACE_L() { return GetToken(TemplateParser.BRACE_L, 0); }
		public ITerminalNode BRACE_R() { return GetToken(TemplateParser.BRACE_R, 0); }
		public ITerminalNode PARENTHESES_L() { return GetToken(TemplateParser.PARENTHESES_L, 0); }
		public ITerminalNode PARENTHESES_R() { return GetToken(TemplateParser.PARENTHESES_R, 0); }
		public ITerminalNode DO() { return GetToken(TemplateParser.DO, 0); }
		public ITerminalNode WHILE() { return GetToken(TemplateParser.WHILE, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public CodeContext[] code() {
			return GetRuleContexts<CodeContext>();
		}
		public CodeContext code(int i) {
			return GetRuleContext<CodeContext>(i);
		}
		public DowhileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dowhile; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterDowhile(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitDowhile(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDowhile(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DowhileContext dowhile() {
		DowhileContext _localctx = new DowhileContext(Context, State);
		EnterRule(_localctx, 14, RULE_dowhile);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 103; _localctx.keywordA = Match(DO);
			State = 104; Match(BRACE_L);
			State = 108;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TEXT) | (1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << VAR) | (1L << IF) | (1L << SWITCH) | (1L << WHILE) | (1L << DO) | (1L << FOR) | (1L << FOREACH) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << IDENT))) != 0)) {
				{
				{
				State = 105; code();
				}
				}
				State = 110;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 111; Match(BRACE_R);
			State = 112; _localctx.keywordB = Match(WHILE);
			State = 113; Match(PARENTHESES_L);
			State = 114; _localctx.condition = expr(0);
			State = 115; Match(PARENTHESES_R);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForContext : ParserRuleContext {
		public IToken keyword;
		public ExprContext expr1;
		public ExprContext expr2;
		public ExprContext expr3;
		public ITerminalNode PARENTHESES_L() { return GetToken(TemplateParser.PARENTHESES_L, 0); }
		public ITerminalNode[] SEMICOLON() { return GetTokens(TemplateParser.SEMICOLON); }
		public ITerminalNode SEMICOLON(int i) {
			return GetToken(TemplateParser.SEMICOLON, i);
		}
		public ITerminalNode PARENTHESES_R() { return GetToken(TemplateParser.PARENTHESES_R, 0); }
		public ITerminalNode BRACE_L() { return GetToken(TemplateParser.BRACE_L, 0); }
		public ITerminalNode BRACE_R() { return GetToken(TemplateParser.BRACE_R, 0); }
		public ITerminalNode FOR() { return GetToken(TemplateParser.FOR, 0); }
		public CodeContext[] code() {
			return GetRuleContexts<CodeContext>();
		}
		public CodeContext code(int i) {
			return GetRuleContext<CodeContext>(i);
		}
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ForContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_for; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterFor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitFor(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFor(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ForContext @for() {
		ForContext _localctx = new ForContext(Context, State);
		EnterRule(_localctx, 16, RULE_for);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 117; _localctx.keyword = Match(FOR);
			State = 118; Match(PARENTHESES_L);
			State = 120;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << IDENT))) != 0)) {
				{
				State = 119; _localctx.expr1 = expr(0);
				}
			}

			State = 122; Match(SEMICOLON);
			State = 124;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << IDENT))) != 0)) {
				{
				State = 123; _localctx.expr2 = expr(0);
				}
			}

			State = 126; Match(SEMICOLON);
			State = 128;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << IDENT))) != 0)) {
				{
				State = 127; _localctx.expr3 = expr(0);
				}
			}

			State = 130; Match(PARENTHESES_R);
			State = 131; Match(BRACE_L);
			State = 135;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TEXT) | (1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << VAR) | (1L << IF) | (1L << SWITCH) | (1L << WHILE) | (1L << DO) | (1L << FOR) | (1L << FOREACH) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << IDENT))) != 0)) {
				{
				{
				State = 132; code();
				}
				}
				State = 137;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 138; Match(BRACE_R);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ForeachContext : ParserRuleContext {
		public IToken keywordA;
		public IToken keywordB;
		public ITerminalNode PARENTHESES_L() { return GetToken(TemplateParser.PARENTHESES_L, 0); }
		public CodeContext[] code() {
			return GetRuleContexts<CodeContext>();
		}
		public CodeContext code(int i) {
			return GetRuleContext<CodeContext>(i);
		}
		public ITerminalNode PARENTHESES_R() { return GetToken(TemplateParser.PARENTHESES_R, 0); }
		public ITerminalNode BRACE_L() { return GetToken(TemplateParser.BRACE_L, 0); }
		public ITerminalNode BRACE_R() { return GetToken(TemplateParser.BRACE_R, 0); }
		public ITerminalNode FOREACH() { return GetToken(TemplateParser.FOREACH, 0); }
		public ITerminalNode IN() { return GetToken(TemplateParser.IN, 0); }
		public ForeachContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_foreach; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterForeach(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitForeach(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitForeach(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ForeachContext @foreach() {
		ForeachContext _localctx = new ForeachContext(Context, State);
		EnterRule(_localctx, 18, RULE_foreach);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 140; _localctx.keywordA = Match(FOREACH);
			State = 141; Match(PARENTHESES_L);
			State = 142; code();
			State = 143; _localctx.keywordB = Match(IN);
			State = 144; code();
			State = 145; Match(PARENTHESES_R);
			State = 146; Match(BRACE_L);
			State = 150;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << TEXT) | (1L << INTEGER) | (1L << FLOAT) | (1L << BOOL) | (1L << STRING) | (1L << INCREMENT) | (1L << DECREMENT) | (1L << SUB) | (1L << PARENTHESES_L) | (1L << LOGIC_NOT) | (1L << BIT_INVERT) | (1L << VAR) | (1L << IF) | (1L << SWITCH) | (1L << WHILE) | (1L << DO) | (1L << FOR) | (1L << FOREACH) | (1L << BREAK) | (1L << CONTINUE) | (1L << RETURN) | (1L << IDENT))) != 0)) {
				{
				{
				State = 147; code();
				}
				}
				State = 152;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 153; Match(BRACE_R);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext r;
		public ExprContext l;
		public ExprCallContext call;
		public ExprPropContext prop;
		public IToken op;
		public IToken t;
		public ExprValueContext v;
		public ITerminalNode PARENTHESES_L() { return GetToken(TemplateParser.PARENTHESES_L, 0); }
		public ITerminalNode PARENTHESES_R() { return GetToken(TemplateParser.PARENTHESES_R, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ExprCallContext exprCall() {
			return GetRuleContext<ExprCallContext>(0);
		}
		public ExprPropContext exprProp() {
			return GetRuleContext<ExprPropContext>(0);
		}
		public ITerminalNode SUB() { return GetToken(TemplateParser.SUB, 0); }
		public ITerminalNode IDENT() { return GetToken(TemplateParser.IDENT, 0); }
		public ITerminalNode INCREMENT() { return GetToken(TemplateParser.INCREMENT, 0); }
		public ITerminalNode DECREMENT() { return GetToken(TemplateParser.DECREMENT, 0); }
		public ITerminalNode LOGIC_NOT() { return GetToken(TemplateParser.LOGIC_NOT, 0); }
		public ITerminalNode BIT_INVERT() { return GetToken(TemplateParser.BIT_INVERT, 0); }
		public ExprValueContext exprValue() {
			return GetRuleContext<ExprValueContext>(0);
		}
		public ITerminalNode MUL() { return GetToken(TemplateParser.MUL, 0); }
		public ITerminalNode DIV() { return GetToken(TemplateParser.DIV, 0); }
		public ITerminalNode MOD() { return GetToken(TemplateParser.MOD, 0); }
		public ITerminalNode ADD() { return GetToken(TemplateParser.ADD, 0); }
		public ITerminalNode SHIFTL() { return GetToken(TemplateParser.SHIFTL, 0); }
		public ITerminalNode SHIFTR() { return GetToken(TemplateParser.SHIFTR, 0); }
		public ITerminalNode LESS() { return GetToken(TemplateParser.LESS, 0); }
		public ITerminalNode LESSEQUAL() { return GetToken(TemplateParser.LESSEQUAL, 0); }
		public ITerminalNode GREATER() { return GetToken(TemplateParser.GREATER, 0); }
		public ITerminalNode GREATEREQUAL() { return GetToken(TemplateParser.GREATEREQUAL, 0); }
		public ITerminalNode EQUAL() { return GetToken(TemplateParser.EQUAL, 0); }
		public ITerminalNode NOTEQUAL() { return GetToken(TemplateParser.NOTEQUAL, 0); }
		public ITerminalNode BIT_AND() { return GetToken(TemplateParser.BIT_AND, 0); }
		public ITerminalNode BIT_XOR() { return GetToken(TemplateParser.BIT_XOR, 0); }
		public ITerminalNode BIT_OR() { return GetToken(TemplateParser.BIT_OR, 0); }
		public ITerminalNode LOGIC_AND() { return GetToken(TemplateParser.LOGIC_AND, 0); }
		public ITerminalNode LOGIC_OR() { return GetToken(TemplateParser.LOGIC_OR, 0); }
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 20;
		EnterRecursionRule(_localctx, 20, RULE_expr, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 177;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 156; Match(PARENTHESES_L);
				State = 157; _localctx.r = expr(0);
				State = 158; Match(PARENTHESES_R);
				}
				break;
			case 2:
				{
				State = 160; _localctx.call = exprCall();
				}
				break;
			case 3:
				{
				State = 161; _localctx.prop = exprProp();
				}
				break;
			case 4:
				{
				State = 162; _localctx.op = Match(SUB);
				State = 163; _localctx.r = expr(27);
				}
				break;
			case 5:
				{
				State = 164; Match(PARENTHESES_L);
				State = 165; _localctx.t = Match(IDENT);
				State = 166; Match(PARENTHESES_R);
				State = 167; _localctx.r = expr(26);
				}
				break;
			case 6:
				{
				State = 168; _localctx.op = Match(INCREMENT);
				State = 169; _localctx.r = expr(25);
				}
				break;
			case 7:
				{
				State = 170; _localctx.op = Match(DECREMENT);
				State = 171; _localctx.r = expr(23);
				}
				break;
			case 8:
				{
				State = 172; _localctx.op = Match(LOGIC_NOT);
				State = 173; _localctx.r = expr(21);
				}
				break;
			case 9:
				{
				State = 174; _localctx.op = Match(BIT_INVERT);
				State = 175; _localctx.r = expr(20);
				}
				break;
			case 10:
				{
				State = 176; _localctx.v = exprValue();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 239;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 237;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
					case 1:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 179;
						if (!(Precpred(Context, 19))) throw new FailedPredicateException(this, "Precpred(Context, 19)");
						State = 180; _localctx.op = Match(MUL);
						State = 181; _localctx.r = expr(20);
						}
						break;
					case 2:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 182;
						if (!(Precpred(Context, 18))) throw new FailedPredicateException(this, "Precpred(Context, 18)");
						State = 183; _localctx.op = Match(DIV);
						State = 184; _localctx.r = expr(19);
						}
						break;
					case 3:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 185;
						if (!(Precpred(Context, 17))) throw new FailedPredicateException(this, "Precpred(Context, 17)");
						State = 186; _localctx.op = Match(MOD);
						State = 187; _localctx.r = expr(18);
						}
						break;
					case 4:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 188;
						if (!(Precpred(Context, 16))) throw new FailedPredicateException(this, "Precpred(Context, 16)");
						State = 189; _localctx.op = Match(ADD);
						State = 190; _localctx.r = expr(17);
						}
						break;
					case 5:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 191;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 192; _localctx.op = Match(SUB);
						State = 193; _localctx.r = expr(16);
						}
						break;
					case 6:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 194;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 195; _localctx.op = Match(SHIFTL);
						State = 196; _localctx.r = expr(15);
						}
						break;
					case 7:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 197;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 198; _localctx.op = Match(SHIFTR);
						State = 199; _localctx.r = expr(14);
						}
						break;
					case 8:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 200;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 201; _localctx.op = Match(LESS);
						State = 202; _localctx.r = expr(13);
						}
						break;
					case 9:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 203;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 204; _localctx.op = Match(LESSEQUAL);
						State = 205; _localctx.r = expr(12);
						}
						break;
					case 10:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 206;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 207; _localctx.op = Match(GREATER);
						State = 208; _localctx.r = expr(11);
						}
						break;
					case 11:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 209;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 210; _localctx.op = Match(GREATEREQUAL);
						State = 211; _localctx.r = expr(10);
						}
						break;
					case 12:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 212;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 213; _localctx.op = Match(EQUAL);
						State = 214; _localctx.r = expr(9);
						}
						break;
					case 13:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 215;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 216; _localctx.op = Match(NOTEQUAL);
						State = 217; _localctx.r = expr(8);
						}
						break;
					case 14:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 218;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 219; _localctx.op = Match(BIT_AND);
						State = 220; _localctx.r = expr(7);
						}
						break;
					case 15:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 221;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 222; _localctx.op = Match(BIT_XOR);
						State = 223; _localctx.r = expr(6);
						}
						break;
					case 16:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 224;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 225; _localctx.op = Match(BIT_OR);
						State = 226; _localctx.r = expr(5);
						}
						break;
					case 17:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 227;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 228; _localctx.op = Match(LOGIC_AND);
						State = 229; _localctx.r = expr(4);
						}
						break;
					case 18:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.l = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 230;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 231; _localctx.op = Match(LOGIC_OR);
						State = 232; _localctx.r = expr(3);
						}
						break;
					case 19:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.r = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 233;
						if (!(Precpred(Context, 24))) throw new FailedPredicateException(this, "Precpred(Context, 24)");
						State = 234; _localctx.op = Match(INCREMENT);
						}
						break;
					case 20:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						_localctx.r = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 235;
						if (!(Precpred(Context, 22))) throw new FailedPredicateException(this, "Precpred(Context, 22)");
						State = 236; _localctx.op = Match(DECREMENT);
						}
						break;
					}
					} 
				}
				State = 241;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ExprCallContext : ParserRuleContext {
		public IToken _IDENT;
		public IList<IToken> _names = new List<IToken>();
		public IToken op;
		public ExprContext _expr;
		public IList<ExprContext> _args = new List<ExprContext>();
		public ITerminalNode PARENTHESES_L() { return GetToken(TemplateParser.PARENTHESES_L, 0); }
		public ITerminalNode PARENTHESES_R() { return GetToken(TemplateParser.PARENTHESES_R, 0); }
		public ITerminalNode[] IDENT() { return GetTokens(TemplateParser.IDENT); }
		public ITerminalNode IDENT(int i) {
			return GetToken(TemplateParser.IDENT, i);
		}
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode[] DOT() { return GetTokens(TemplateParser.DOT); }
		public ITerminalNode DOT(int i) {
			return GetToken(TemplateParser.DOT, i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(TemplateParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(TemplateParser.COMMA, i);
		}
		public ExprCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_exprCall; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterExprCall(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitExprCall(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExprCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprCallContext exprCall() {
		ExprCallContext _localctx = new ExprCallContext(Context, State);
		EnterRule(_localctx, 22, RULE_exprCall);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 242; _localctx._IDENT = Match(IDENT);
			_localctx._names.Add(_localctx._IDENT);
			State = 247;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==DOT) {
				{
				{
				State = 243; _localctx.op = Match(DOT);
				State = 244; _localctx._IDENT = Match(IDENT);
				_localctx._names.Add(_localctx._IDENT);
				}
				}
				State = 249;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 250; Match(PARENTHESES_L);
			{
			State = 251; _localctx._expr = expr(0);
			_localctx._args.Add(_localctx._expr);
			State = 256;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 252; Match(COMMA);
				State = 253; _localctx._expr = expr(0);
				_localctx._args.Add(_localctx._expr);
				}
				}
				State = 258;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
			State = 259; Match(PARENTHESES_R);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprPropContext : ParserRuleContext {
		public IToken _IDENT;
		public IList<IToken> _names = new List<IToken>();
		public IToken op;
		public ITerminalNode[] IDENT() { return GetTokens(TemplateParser.IDENT); }
		public ITerminalNode IDENT(int i) {
			return GetToken(TemplateParser.IDENT, i);
		}
		public ITerminalNode[] DOT() { return GetTokens(TemplateParser.DOT); }
		public ITerminalNode DOT(int i) {
			return GetToken(TemplateParser.DOT, i);
		}
		public ExprPropContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_exprProp; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterExprProp(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitExprProp(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExprProp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprPropContext exprProp() {
		ExprPropContext _localctx = new ExprPropContext(Context, State);
		EnterRule(_localctx, 24, RULE_exprProp);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 261; _localctx._IDENT = Match(IDENT);
			_localctx._names.Add(_localctx._IDENT);
			State = 266;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,18,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 262; _localctx.op = Match(DOT);
					State = 263; _localctx._IDENT = Match(IDENT);
					_localctx._names.Add(_localctx._IDENT);
					}
					} 
				}
				State = 268;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,18,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprValueContext : ParserRuleContext {
		public IToken integerValue;
		public IToken floatValue;
		public IToken boolValue;
		public IToken stringValue;
		public ITerminalNode INTEGER() { return GetToken(TemplateParser.INTEGER, 0); }
		public ITerminalNode FLOAT() { return GetToken(TemplateParser.FLOAT, 0); }
		public ITerminalNode BOOL() { return GetToken(TemplateParser.BOOL, 0); }
		public ITerminalNode STRING() { return GetToken(TemplateParser.STRING, 0); }
		public ExprValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_exprValue; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.EnterExprValue(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITemplateParserListener typedListener = listener as ITemplateParserListener;
			if (typedListener != null) typedListener.ExitExprValue(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITemplateParserVisitor<TResult> typedVisitor = visitor as ITemplateParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExprValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprValueContext exprValue() {
		ExprValueContext _localctx = new ExprValueContext(Context, State);
		EnterRule(_localctx, 26, RULE_exprValue);
		try {
			State = 273;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INTEGER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 269; _localctx.integerValue = Match(INTEGER);
				}
				break;
			case FLOAT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 270; _localctx.floatValue = Match(FLOAT);
				}
				break;
			case BOOL:
				EnterOuterAlt(_localctx, 3);
				{
				State = 271; _localctx.boolValue = Match(BOOL);
				}
				break;
			case STRING:
				EnterOuterAlt(_localctx, 4);
				{
				State = 272; _localctx.stringValue = Match(STRING);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 10: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 19);
		case 1: return Precpred(Context, 18);
		case 2: return Precpred(Context, 17);
		case 3: return Precpred(Context, 16);
		case 4: return Precpred(Context, 15);
		case 5: return Precpred(Context, 14);
		case 6: return Precpred(Context, 13);
		case 7: return Precpred(Context, 12);
		case 8: return Precpred(Context, 11);
		case 9: return Precpred(Context, 10);
		case 10: return Precpred(Context, 9);
		case 11: return Precpred(Context, 8);
		case 12: return Precpred(Context, 7);
		case 13: return Precpred(Context, 6);
		case 14: return Precpred(Context, 5);
		case 15: return Precpred(Context, 4);
		case 16: return Precpred(Context, 3);
		case 17: return Precpred(Context, 2);
		case 18: return Precpred(Context, 24);
		case 19: return Precpred(Context, 22);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x41', '\x116', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x3', '\x2', '\a', '\x2', ' ', '\n', 
		'\x2', '\f', '\x2', '\xE', '\x2', '#', '\v', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x5', '\x3', '\x31', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', 
		'\x39', '\n', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', 
		'\x43', '\n', '\x6', '\f', '\x6', '\xE', '\x6', '\x46', '\v', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x5', '\a', 'T', '\n', '\a', '\a', '\a', 'V', '\n', '\a', '\f', 
		'\a', '\xE', '\a', 'Y', '\v', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\a', 
		'\b', '\x63', '\n', '\b', '\f', '\b', '\xE', '\b', '\x66', '\v', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\a', 
		'\t', 'm', '\n', '\t', '\f', '\t', '\xE', '\t', 'p', '\v', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x5', '\n', '{', '\n', '\n', '\x3', 
		'\n', '\x3', '\n', '\x5', '\n', '\x7F', '\n', '\n', '\x3', '\n', '\x3', 
		'\n', '\x5', '\n', '\x83', '\n', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\a', '\n', '\x88', '\n', '\n', '\f', '\n', '\xE', '\n', '\x8B', 
		'\v', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\a', '\v', '\x97', '\n', '\v', '\f', '\v', '\xE', '\v', '\x9A', '\v', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x5', '\f', '\xB4', '\n', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\a', '\f', '\xF0', '\n', '\f', '\f', 
		'\f', '\xE', '\f', '\xF3', '\v', '\f', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\a', '\r', '\xF8', '\n', '\r', '\f', '\r', '\xE', '\r', '\xFB', 
		'\v', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\a', 
		'\r', '\x101', '\n', '\r', '\f', '\r', '\xE', '\r', '\x104', '\v', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\a', 
		'\xE', '\x10B', '\n', '\xE', '\f', '\xE', '\xE', '\xE', '\x10E', '\v', 
		'\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x5', 
		'\xF', '\x114', '\n', '\xF', '\x3', '\xF', '\x2', '\x3', '\x16', '\x10', 
		'\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', 
		'\x16', '\x18', '\x1A', '\x1C', '\x2', '\x2', '\x2', '\x141', '\x2', '!', 
		'\x3', '\x2', '\x2', '\x2', '\x4', '\x30', '\x3', '\x2', '\x2', '\x2', 
		'\x6', '\x32', '\x3', '\x2', '\x2', '\x2', '\b', '\x34', '\x3', '\x2', 
		'\x2', '\x2', '\n', '<', '\x3', '\x2', '\x2', '\x2', '\f', 'I', '\x3', 
		'\x2', '\x2', '\x2', '\xE', '\\', '\x3', '\x2', '\x2', '\x2', '\x10', 
		'i', '\x3', '\x2', '\x2', '\x2', '\x12', 'w', '\x3', '\x2', '\x2', '\x2', 
		'\x14', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x16', '\xB3', '\x3', '\x2', 
		'\x2', '\x2', '\x18', '\xF4', '\x3', '\x2', '\x2', '\x2', '\x1A', '\x107', 
		'\x3', '\x2', '\x2', '\x2', '\x1C', '\x113', '\x3', '\x2', '\x2', '\x2', 
		'\x1E', ' ', '\x5', '\x4', '\x3', '\x2', '\x1F', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', ' ', '#', '\x3', '\x2', '\x2', '\x2', '!', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '!', '\"', '\x3', '\x2', '\x2', '\x2', '\"', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '#', '!', '\x3', '\x2', '\x2', '\x2', '$', 
		'\x31', '\x5', '\b', '\x5', '\x2', '%', '\x31', '\x5', '\n', '\x6', '\x2', 
		'&', '\x31', '\x5', '\f', '\a', '\x2', '\'', '\x31', '\x5', '\xE', '\b', 
		'\x2', '(', '\x31', '\x5', '\x10', '\t', '\x2', ')', '\x31', '\x5', '\x12', 
		'\n', '\x2', '*', '\x31', '\x5', '\x14', '\v', '\x2', '+', '\x31', '\x5', 
		'\x16', '\f', '\x2', ',', '\x31', '\x5', '\x6', '\x4', '\x2', '-', '\x31', 
		'\a', '<', '\x2', '\x2', '.', '\x31', '\a', '=', '\x2', '\x2', '/', '\x31', 
		'\a', '>', '\x2', '\x2', '\x30', '$', '\x3', '\x2', '\x2', '\x2', '\x30', 
		'%', '\x3', '\x2', '\x2', '\x2', '\x30', '&', '\x3', '\x2', '\x2', '\x2', 
		'\x30', '\'', '\x3', '\x2', '\x2', '\x2', '\x30', '(', '\x3', '\x2', '\x2', 
		'\x2', '\x30', ')', '\x3', '\x2', '\x2', '\x2', '\x30', '*', '\x3', '\x2', 
		'\x2', '\x2', '\x30', '+', '\x3', '\x2', '\x2', '\x2', '\x30', ',', '\x3', 
		'\x2', '\x2', '\x2', '\x30', '-', '\x3', '\x2', '\x2', '\x2', '\x30', 
		'.', '\x3', '\x2', '\x2', '\x2', '\x30', '/', '\x3', '\x2', '\x2', '\x2', 
		'\x31', '\x5', '\x3', '\x2', '\x2', '\x2', '\x32', '\x33', '\a', '\x4', 
		'\x2', '\x2', '\x33', '\a', '\x3', '\x2', '\x2', '\x2', '\x34', '\x35', 
		'\a', '\x33', '\x2', '\x2', '\x35', '\x38', '\a', '?', '\x2', '\x2', '\x36', 
		'\x37', '\a', '*', '\x2', '\x2', '\x37', '\x39', '\x5', '\x16', '\f', 
		'\x2', '\x38', '\x36', '\x3', '\x2', '\x2', '\x2', '\x38', '\x39', '\x3', 
		'\x2', '\x2', '\x2', '\x39', ':', '\x3', '\x2', '\x2', '\x2', ':', ';', 
		'\a', '\x32', '\x2', '\x2', ';', '\t', '\x3', '\x2', '\x2', '\x2', '<', 
		'=', '\a', '\x34', '\x2', '\x2', '=', '>', '\a', '\x1D', '\x2', '\x2', 
		'>', '?', '\x5', '\x16', '\f', '\x2', '?', '@', '\a', '\x1E', '\x2', '\x2', 
		'@', '\x44', '\a', '\x14', '\x2', '\x2', '\x41', '\x43', '\x5', '\x4', 
		'\x3', '\x2', '\x42', '\x41', '\x3', '\x2', '\x2', '\x2', '\x43', '\x46', 
		'\x3', '\x2', '\x2', '\x2', '\x44', '\x42', '\x3', '\x2', '\x2', '\x2', 
		'\x44', '\x45', '\x3', '\x2', '\x2', '\x2', '\x45', 'G', '\x3', '\x2', 
		'\x2', '\x2', '\x46', '\x44', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\a', 
		'\x15', '\x2', '\x2', 'H', '\v', '\x3', '\x2', '\x2', '\x2', 'I', 'J', 
		'\a', '\x35', '\x2', '\x2', 'J', 'K', '\a', '\x1D', '\x2', '\x2', 'K', 
		'L', '\x5', '\x16', '\f', '\x2', 'L', 'M', '\a', '\x1E', '\x2', '\x2', 
		'M', 'W', '\a', '\x14', '\x2', '\x2', 'N', 'O', '\a', '\x36', '\x2', '\x2', 
		'O', 'P', '\x5', '\x16', '\f', '\x2', 'P', 'Q', '\a', '\x31', '\x2', '\x2', 
		'Q', 'S', '\x5', '\x16', '\f', '\x2', 'R', 'T', '\a', '<', '\x2', '\x2', 
		'S', 'R', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\x3', '\x2', '\x2', '\x2', 
		'T', 'V', '\x3', '\x2', '\x2', '\x2', 'U', 'N', '\x3', '\x2', '\x2', '\x2', 
		'V', 'Y', '\x3', '\x2', '\x2', '\x2', 'W', 'U', '\x3', '\x2', '\x2', '\x2', 
		'W', 'X', '\x3', '\x2', '\x2', '\x2', 'X', 'Z', '\x3', '\x2', '\x2', '\x2', 
		'Y', 'W', '\x3', '\x2', '\x2', '\x2', 'Z', '[', '\a', '\x15', '\x2', '\x2', 
		'[', '\r', '\x3', '\x2', '\x2', '\x2', '\\', ']', '\a', '\x37', '\x2', 
		'\x2', ']', '^', '\a', '\x1D', '\x2', '\x2', '^', '_', '\x5', '\x16', 
		'\f', '\x2', '_', '`', '\a', '\x1E', '\x2', '\x2', '`', '\x64', '\a', 
		'\x14', '\x2', '\x2', '\x61', '\x63', '\x5', '\x4', '\x3', '\x2', '\x62', 
		'\x61', '\x3', '\x2', '\x2', '\x2', '\x63', '\x66', '\x3', '\x2', '\x2', 
		'\x2', '\x64', '\x62', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\x3', 
		'\x2', '\x2', '\x2', '\x65', 'g', '\x3', '\x2', '\x2', '\x2', '\x66', 
		'\x64', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', '\x15', '\x2', '\x2', 
		'h', '\xF', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', '\x38', '\x2', 
		'\x2', 'j', 'n', '\a', '\x14', '\x2', '\x2', 'k', 'm', '\x5', '\x4', '\x3', 
		'\x2', 'l', 'k', '\x3', '\x2', '\x2', '\x2', 'm', 'p', '\x3', '\x2', '\x2', 
		'\x2', 'n', 'l', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\x3', '\x2', '\x2', 
		'\x2', 'o', 'q', '\x3', '\x2', '\x2', '\x2', 'p', 'n', '\x3', '\x2', '\x2', 
		'\x2', 'q', 'r', '\a', '\x15', '\x2', '\x2', 'r', 's', '\a', '\x37', '\x2', 
		'\x2', 's', 't', '\a', '\x1D', '\x2', '\x2', 't', 'u', '\x5', '\x16', 
		'\f', '\x2', 'u', 'v', '\a', '\x1E', '\x2', '\x2', 'v', '\x11', '\x3', 
		'\x2', '\x2', '\x2', 'w', 'x', '\a', '\x39', '\x2', '\x2', 'x', 'z', '\a', 
		'\x1D', '\x2', '\x2', 'y', '{', '\x5', '\x16', '\f', '\x2', 'z', 'y', 
		'\x3', '\x2', '\x2', '\x2', 'z', '{', '\x3', '\x2', '\x2', '\x2', '{', 
		'|', '\x3', '\x2', '\x2', '\x2', '|', '~', '\a', '\x32', '\x2', '\x2', 
		'}', '\x7F', '\x5', '\x16', '\f', '\x2', '~', '}', '\x3', '\x2', '\x2', 
		'\x2', '~', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', '\x3', 
		'\x2', '\x2', '\x2', '\x80', '\x82', '\a', '\x32', '\x2', '\x2', '\x81', 
		'\x83', '\x5', '\x16', '\f', '\x2', '\x82', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\x82', '\x83', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', '\x3', 
		'\x2', '\x2', '\x2', '\x84', '\x85', '\a', '\x1E', '\x2', '\x2', '\x85', 
		'\x89', '\a', '\x14', '\x2', '\x2', '\x86', '\x88', '\x5', '\x4', '\x3', 
		'\x2', '\x87', '\x86', '\x3', '\x2', '\x2', '\x2', '\x88', '\x8B', '\x3', 
		'\x2', '\x2', '\x2', '\x89', '\x87', '\x3', '\x2', '\x2', '\x2', '\x89', 
		'\x8A', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8C', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '\x89', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\a', 
		'\x15', '\x2', '\x2', '\x8D', '\x13', '\x3', '\x2', '\x2', '\x2', '\x8E', 
		'\x8F', '\a', ':', '\x2', '\x2', '\x8F', '\x90', '\a', '\x1D', '\x2', 
		'\x2', '\x90', '\x91', '\x5', '\x4', '\x3', '\x2', '\x91', '\x92', '\a', 
		';', '\x2', '\x2', '\x92', '\x93', '\x5', '\x4', '\x3', '\x2', '\x93', 
		'\x94', '\a', '\x1E', '\x2', '\x2', '\x94', '\x98', '\a', '\x14', '\x2', 
		'\x2', '\x95', '\x97', '\x5', '\x4', '\x3', '\x2', '\x96', '\x95', '\x3', 
		'\x2', '\x2', '\x2', '\x97', '\x9A', '\x3', '\x2', '\x2', '\x2', '\x98', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', '\x3', '\x2', '\x2', 
		'\x2', '\x99', '\x9B', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x98', '\x3', 
		'\x2', '\x2', '\x2', '\x9B', '\x9C', '\a', '\x15', '\x2', '\x2', '\x9C', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\b', '\f', '\x1', 
		'\x2', '\x9E', '\x9F', '\a', '\x1D', '\x2', '\x2', '\x9F', '\xA0', '\x5', 
		'\x16', '\f', '\x2', '\xA0', '\xA1', '\a', '\x1E', '\x2', '\x2', '\xA1', 
		'\xB4', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xB4', '\x5', '\x18', '\r', 
		'\x2', '\xA3', '\xB4', '\x5', '\x1A', '\xE', '\x2', '\xA4', '\xA5', '\a', 
		'\x1C', '\x2', '\x2', '\xA5', '\xB4', '\x5', '\x16', '\f', '\x1D', '\xA6', 
		'\xA7', '\a', '\x1D', '\x2', '\x2', '\xA7', '\xA8', '\a', '?', '\x2', 
		'\x2', '\xA8', '\xA9', '\a', '\x1E', '\x2', '\x2', '\xA9', '\xB4', '\x5', 
		'\x16', '\f', '\x1C', '\xAA', '\xAB', '\a', '\x16', '\x2', '\x2', '\xAB', 
		'\xB4', '\x5', '\x16', '\f', '\x1B', '\xAC', '\xAD', '\a', '\x17', '\x2', 
		'\x2', '\xAD', '\xB4', '\x5', '\x16', '\f', '\x19', '\xAE', '\xAF', '\a', 
		'\"', '\x2', '\x2', '\xAF', '\xB4', '\x5', '\x16', '\f', '\x17', '\xB0', 
		'\xB1', '\a', '#', '\x2', '\x2', '\xB1', '\xB4', '\x5', '\x16', '\f', 
		'\x16', '\xB2', '\xB4', '\x5', '\x1C', '\xF', '\x2', '\xB3', '\x9D', '\x3', 
		'\x2', '\x2', '\x2', '\xB3', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xB3', 
		'\xA3', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xA4', '\x3', '\x2', '\x2', 
		'\x2', '\xB3', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xAA', '\x3', 
		'\x2', '\x2', '\x2', '\xB3', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xB3', 
		'\xAE', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB0', '\x3', '\x2', '\x2', 
		'\x2', '\xB3', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xF1', '\x3', 
		'\x2', '\x2', '\x2', '\xB5', '\xB6', '\f', '\x15', '\x2', '\x2', '\xB6', 
		'\xB7', '\a', '\x18', '\x2', '\x2', '\xB7', '\xF0', '\x5', '\x16', '\f', 
		'\x16', '\xB8', '\xB9', '\f', '\x14', '\x2', '\x2', '\xB9', '\xBA', '\a', 
		'\x19', '\x2', '\x2', '\xBA', '\xF0', '\x5', '\x16', '\f', '\x15', '\xBB', 
		'\xBC', '\f', '\x13', '\x2', '\x2', '\xBC', '\xBD', '\a', '\x1A', '\x2', 
		'\x2', '\xBD', '\xF0', '\x5', '\x16', '\f', '\x14', '\xBE', '\xBF', '\f', 
		'\x12', '\x2', '\x2', '\xBF', '\xC0', '\a', '\x1B', '\x2', '\x2', '\xC0', 
		'\xF0', '\x5', '\x16', '\f', '\x13', '\xC1', '\xC2', '\f', '\x11', '\x2', 
		'\x2', '\xC2', '\xC3', '\a', '\x1C', '\x2', '\x2', '\xC3', '\xF0', '\x5', 
		'\x16', '\f', '\x12', '\xC4', '\xC5', '\f', '\x10', '\x2', '\x2', '\xC5', 
		'\xC6', '\a', '$', '\x2', '\x2', '\xC6', '\xF0', '\x5', '\x16', '\f', 
		'\x11', '\xC7', '\xC8', '\f', '\xF', '\x2', '\x2', '\xC8', '\xC9', '\a', 
		'%', '\x2', '\x2', '\xC9', '\xF0', '\x5', '\x16', '\f', '\x10', '\xCA', 
		'\xCB', '\f', '\xE', '\x2', '\x2', '\xCB', '\xCC', '\a', '&', '\x2', '\x2', 
		'\xCC', '\xF0', '\x5', '\x16', '\f', '\xF', '\xCD', '\xCE', '\f', '\r', 
		'\x2', '\x2', '\xCE', '\xCF', '\a', '\'', '\x2', '\x2', '\xCF', '\xF0', 
		'\x5', '\x16', '\f', '\xE', '\xD0', '\xD1', '\f', '\f', '\x2', '\x2', 
		'\xD1', '\xD2', '\a', '(', '\x2', '\x2', '\xD2', '\xF0', '\x5', '\x16', 
		'\f', '\r', '\xD3', '\xD4', '\f', '\v', '\x2', '\x2', '\xD4', '\xD5', 
		'\a', ')', '\x2', '\x2', '\xD5', '\xF0', '\x5', '\x16', '\f', '\f', '\xD6', 
		'\xD7', '\f', '\n', '\x2', '\x2', '\xD7', '\xD8', '\a', '*', '\x2', '\x2', 
		'\xD8', '\xF0', '\x5', '\x16', '\f', '\v', '\xD9', '\xDA', '\f', '\t', 
		'\x2', '\x2', '\xDA', '\xDB', '\a', '!', '\x2', '\x2', '\xDB', '\xF0', 
		'\x5', '\x16', '\f', '\n', '\xDC', '\xDD', '\f', '\b', '\x2', '\x2', '\xDD', 
		'\xDE', '\a', '-', '\x2', '\x2', '\xDE', '\xF0', '\x5', '\x16', '\f', 
		'\t', '\xDF', '\xE0', '\f', '\a', '\x2', '\x2', '\xE0', '\xE1', '\a', 
		'/', '\x2', '\x2', '\xE1', '\xF0', '\x5', '\x16', '\f', '\b', '\xE2', 
		'\xE3', '\f', '\x6', '\x2', '\x2', '\xE3', '\xE4', '\a', '.', '\x2', '\x2', 
		'\xE4', '\xF0', '\x5', '\x16', '\f', '\a', '\xE5', '\xE6', '\f', '\x5', 
		'\x2', '\x2', '\xE6', '\xE7', '\a', '+', '\x2', '\x2', '\xE7', '\xF0', 
		'\x5', '\x16', '\f', '\x6', '\xE8', '\xE9', '\f', '\x4', '\x2', '\x2', 
		'\xE9', '\xEA', '\a', ',', '\x2', '\x2', '\xEA', '\xF0', '\x5', '\x16', 
		'\f', '\x5', '\xEB', '\xEC', '\f', '\x1A', '\x2', '\x2', '\xEC', '\xF0', 
		'\a', '\x16', '\x2', '\x2', '\xED', '\xEE', '\f', '\x18', '\x2', '\x2', 
		'\xEE', '\xF0', '\a', '\x17', '\x2', '\x2', '\xEF', '\xB5', '\x3', '\x2', 
		'\x2', '\x2', '\xEF', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xEF', '\xBB', 
		'\x3', '\x2', '\x2', '\x2', '\xEF', '\xBE', '\x3', '\x2', '\x2', '\x2', 
		'\xEF', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xEF', '\xC4', '\x3', '\x2', 
		'\x2', '\x2', '\xEF', '\xC7', '\x3', '\x2', '\x2', '\x2', '\xEF', '\xCA', 
		'\x3', '\x2', '\x2', '\x2', '\xEF', '\xCD', '\x3', '\x2', '\x2', '\x2', 
		'\xEF', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xEF', '\xD3', '\x3', '\x2', 
		'\x2', '\x2', '\xEF', '\xD6', '\x3', '\x2', '\x2', '\x2', '\xEF', '\xD9', 
		'\x3', '\x2', '\x2', '\x2', '\xEF', '\xDC', '\x3', '\x2', '\x2', '\x2', 
		'\xEF', '\xDF', '\x3', '\x2', '\x2', '\x2', '\xEF', '\xE2', '\x3', '\x2', 
		'\x2', '\x2', '\xEF', '\xE5', '\x3', '\x2', '\x2', '\x2', '\xEF', '\xE8', 
		'\x3', '\x2', '\x2', '\x2', '\xEF', '\xEB', '\x3', '\x2', '\x2', '\x2', 
		'\xEF', '\xED', '\x3', '\x2', '\x2', '\x2', '\xF0', '\xF3', '\x3', '\x2', 
		'\x2', '\x2', '\xF1', '\xEF', '\x3', '\x2', '\x2', '\x2', '\xF1', '\xF2', 
		'\x3', '\x2', '\x2', '\x2', '\xF2', '\x17', '\x3', '\x2', '\x2', '\x2', 
		'\xF3', '\xF1', '\x3', '\x2', '\x2', '\x2', '\xF4', '\xF9', '\a', '?', 
		'\x2', '\x2', '\xF5', '\xF6', '\a', '\x1F', '\x2', '\x2', '\xF6', '\xF8', 
		'\a', '?', '\x2', '\x2', '\xF7', '\xF5', '\x3', '\x2', '\x2', '\x2', '\xF8', 
		'\xFB', '\x3', '\x2', '\x2', '\x2', '\xF9', '\xF7', '\x3', '\x2', '\x2', 
		'\x2', '\xF9', '\xFA', '\x3', '\x2', '\x2', '\x2', '\xFA', '\xFC', '\x3', 
		'\x2', '\x2', '\x2', '\xFB', '\xF9', '\x3', '\x2', '\x2', '\x2', '\xFC', 
		'\xFD', '\a', '\x1D', '\x2', '\x2', '\xFD', '\x102', '\x5', '\x16', '\f', 
		'\x2', '\xFE', '\xFF', '\a', ' ', '\x2', '\x2', '\xFF', '\x101', '\x5', 
		'\x16', '\f', '\x2', '\x100', '\xFE', '\x3', '\x2', '\x2', '\x2', '\x101', 
		'\x104', '\x3', '\x2', '\x2', '\x2', '\x102', '\x100', '\x3', '\x2', '\x2', 
		'\x2', '\x102', '\x103', '\x3', '\x2', '\x2', '\x2', '\x103', '\x105', 
		'\x3', '\x2', '\x2', '\x2', '\x104', '\x102', '\x3', '\x2', '\x2', '\x2', 
		'\x105', '\x106', '\a', '\x1E', '\x2', '\x2', '\x106', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '\x107', '\x10C', '\a', '?', '\x2', '\x2', '\x108', 
		'\x109', '\a', '\x1F', '\x2', '\x2', '\x109', '\x10B', '\a', '?', '\x2', 
		'\x2', '\x10A', '\x108', '\x3', '\x2', '\x2', '\x2', '\x10B', '\x10E', 
		'\x3', '\x2', '\x2', '\x2', '\x10C', '\x10A', '\x3', '\x2', '\x2', '\x2', 
		'\x10C', '\x10D', '\x3', '\x2', '\x2', '\x2', '\x10D', '\x1B', '\x3', 
		'\x2', '\x2', '\x2', '\x10E', '\x10C', '\x3', '\x2', '\x2', '\x2', '\x10F', 
		'\x114', '\a', '\x6', '\x2', '\x2', '\x110', '\x114', '\a', '\a', '\x2', 
		'\x2', '\x111', '\x114', '\a', '\b', '\x2', '\x2', '\x112', '\x114', '\a', 
		'\x13', '\x2', '\x2', '\x113', '\x10F', '\x3', '\x2', '\x2', '\x2', '\x113', 
		'\x110', '\x3', '\x2', '\x2', '\x2', '\x113', '\x111', '\x3', '\x2', '\x2', 
		'\x2', '\x113', '\x112', '\x3', '\x2', '\x2', '\x2', '\x114', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\x16', '!', '\x30', '\x38', '\x44', 'S', 
		'W', '\x64', 'n', 'z', '~', '\x82', '\x89', '\x98', '\xB3', '\xEF', '\xF1', 
		'\xF9', '\x102', '\x10C', '\x113',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
