//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Json.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="JsonParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IJsonListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JsonParser.json"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJson([NotNull] JsonParser.JsonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JsonParser.json"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJson([NotNull] JsonParser.JsonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JsonParser.jsonArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonArray([NotNull] JsonParser.JsonArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JsonParser.jsonArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonArray([NotNull] JsonParser.JsonArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JsonParser.jsonObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonObject([NotNull] JsonParser.JsonObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JsonParser.jsonObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonObject([NotNull] JsonParser.JsonObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JsonParser.jsonProp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonProp([NotNull] JsonParser.JsonPropContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JsonParser.jsonProp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonProp([NotNull] JsonParser.JsonPropContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JsonParser.jsonValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsonValue([NotNull] JsonParser.JsonValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JsonParser.jsonValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsonValue([NotNull] JsonParser.JsonValueContext context);
}
