// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ss
{

using global::System;
using global::FlatBuffers;

public struct BB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static BB GetRootAsBB(ByteBuffer _bb) { return GetRootAsBB(_bb, new BB()); }
  public static BB GetRootAsBB(ByteBuffer _bb, BB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public BB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int A { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)1; } }

  public static Offset<BB> CreateBB(FlatBufferBuilder builder,
      int a = 1) {
    builder.StartObject(1);
    BB.AddA(builder, a);
    return BB.EndBB(builder);
  }

  public static void StartBB(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddA(FlatBufferBuilder builder, int a) { builder.AddInt(0, a, 1); }
  public static Offset<BB> EndBB(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<BB>(o);
  }
  public static void FinishBBBuffer(FlatBufferBuilder builder, Offset<BB> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedBBBuffer(FlatBufferBuilder builder, Offset<BB> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
